stages:
  - testing

image: docker:latest

services:
  - docker:dind

before_script:
  - mkdir -p /go/src/gitlab.com/verygoodsoftwarenotvirus/
  - cp -rf /builds/verygoodsoftwarenotvirus/todo
    /go/src/gitlab.com/verygoodsoftwarenotvirus/
  - cd /go/src/gitlab.com/verygoodsoftwarenotvirus/todo
  - apk add --update --no-cache make git gcc musl-dev

unit-tests:
  stage: testing
  image: golang:alpine
  variables:
    GOPATH: '/go'
  script:
    - make coverage.out

integration-tests:
  stage: testing
  variables:
    GOPATH: '/go'
  script:
    - apk add --update --no-cache py-pip openssl curl
    - curl -L
      "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname
      -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - ls -Al /usr/local/bin/docker-compose
    - PATH=$PATH:/usr/local/bin/ make integration-tests
