version: '3.3'
services:
    database:
        image: mariadb:latest
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
            MYSQL_DATABASE: 'todo'
            MYSQL_PASSWORD: 'hunter2'
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_USER: 'dbuser'
        logging:
            driver: none
        ports:
            - 3306:3306
    load-tests:
        environment:
            TARGET_ADDRESS: 'http://todo-server:8888'
        links:
            - todo-server
    todo-server:
        build:
            context: '../../../../'
            dockerfile: 'environments/testing/dockerfiles/integration-server.Dockerfile'
        links:
            - database
            - tracing-server
            - prometheus
            - loki
            - promtail
        volumes:
            - source: '../../../../environments/testing/config_files/integration-tests-mariadb.toml'
              target: '/etc/config.toml'
              type: 'bind'
