version: '3.3'
services:
    load-tests:
        environment:
            TARGET_ADDRESS: 'http://todo-server:8888'
        links:
            - todo-server
        build:
            context: '../../../../'
            dockerfile: 'environments/testing/dockerfiles/load-tests.Dockerfile'
    todo-server:
        environment:
            CONFIGURATION_FILEPATH: '/etc/service.config'
        ports:
            - 80:8888
        build:
            context: '../../../../'
            dockerfile: 'environments/testing/dockerfiles/integration-server.Dockerfile'
        volumes:
            - source: '../../../../environments/testing/config_files/integration-tests-sqlite.toml'
              target: '/etc/service.config'
              type: 'bind'
