---
version: '3.3'
services:
    database:
        image: postgres:latest
        environment:
            POSTGRES_DB: 'todo'
            POSTGRES_PASSWORD: 'hunter2'
            POSTGRES_USER: 'dbuser'
        logging:
            driver: none
        ports:
            - 2345:5432
    load-tests:
        environment:
            TARGET_ADDRESS: 'http://todo-server:8888'
            DB_ADDRESS: 'postgres://dbuser:hunter2@database:5432/todo?sslmode=disable'
            DB_VENDOR: 'postgres'
        links:
            - todo-server
        build:
            context: '../../../../'
            dockerfile: 'environments/testing/dockerfiles/load-tests.Dockerfile'
    todo-server:
        environment:
            CONFIGURATION_FILEPATH: '/etc/config.toml'
        ports:
            - 80:8888
        links:
            - database
        build:
            context: '../../../../'
            dockerfile: 'environments/testing/dockerfiles/integration-server-postgres.Dockerfile'
