version: '3.3'
services:
    load-tests:
        environment:
            TARGET_ADDRESS: 'http://todo-server:8888'
            DB_ADDRESS: '/tmp/db'
            DB_VENDOR: 'sqlite'
        links:
            - todo-server
        build:
            context: '../../../../'
            dockerfile: 'environments/testing/dockerfiles/load-tests.Dockerfile'
    todo-server:
        environment:
            CONFIGURATION_FILEPATH: '/etc/config.toml'
        ports:
            - 80:8888
        build:
            context: '../../../../'
            dockerfile: 'environments/testing/dockerfiles/integration-server-sqlite.Dockerfile'
