
[audit_log]
  enabled = true

[auth]
  cookie_domain = "localhost"
  cookie_lifetime = "24h0m0s"
  cookie_signing_key = "HEREISA32CHARSECRETWHICHISMADEUP"
  debug = false
  enable_user_signup = true
  minimum_password_length = 8
  minimum_username_length = 4

[database]
  connection_details = "postgres://dbuser:hunter2@database:5432/todo?sslmode=disable"
  debug = false
  provider = "postgres"
  run_migrations = true

  [database.create_test_user]
    is_admin = false
    password = "password"
    username = "coverageUser"

[frontend]
  cache_static_files = false
  debug = true
  static_files_directory = "/frontend"

[meta]
  debug = true
  run_mode = "testing"
  startup_deadline = "1m0s"

[metrics]
  database_metrics_collection_interval = "2s"
  runtime_metrics_collection_interval = "2s"

[search]
  items_index_path = "items.bleve"

[server]
  debug = true
  http_port = 8888

[webhooks]
  enabled = false
