
[audit_log]
  enabled = true

[auth]
  debug = false
  enable_user_signup = true
  minimum_password_length = 8
  minimum_username_length = 4

  [auth.cookies]
    domain = "localhost"
    lifetime = "24h0m0s"
    name = "todocookie"
    secure_only = false
    signing_key = "HEREISA32CHARSECRETWHICHISMADEUP"

  [auth.paseto]
    issuer = "todo_service"
    lifetime = "1m0s"
    local_mode_key = [73,29,169,60,171,102,63,213,179,47,246,170,203,52,83,233,128,43,126,134,33,233,174,176,51,232,246,87,237,91,53,170]

[database]
  connection_details = "postgres://dbuser:hunter2@database:5432/todo?sslmode=disable"
  debug = false
  max_ping_attempts = 50
  metrics_collection_interval = "2s"
  provider = "postgres"
  run_migrations = true

  [database.create_test_user]
    hashed_password = "$2a$11$hKBqG0VX94U2osj7axIkGO2j32MZwcIv3F6ONRksXRiLDem8N71Nm"
    is_site_admin = false
    password = "password"
    username = "coverageUser"

[encoding]
  content_type = "application/json"

[frontend]
  cache_static_files = false
  debug = false
  static_files_directory = "/frontend"

[meta]
  debug = true
  run_mode = "testing"

[observability]

  [observability.metrics]
    provider = ""
    runtime_metrics_collection_interval = "1s"

  [observability.tracing]
    provider = ""
    span_collection_probability = 1.0

[search]
  items_index_path = "items.bleve"
  provider = "bleve"

[server]
  debug = true
  http_port = 8888
  startup_deadline = "1m0s"

[uploads]

  [uploads.storage_config]
    bucket_name = "avatars"
    debug = true
    provider = "memory"
    upload_filename_key = "avatar"

[webhooks]
  enabled = true
