
[audit_log]
  enabled = true

[auth]
  cookie_domain = "localhost"
  cookie_lifetime = "24h0m0s"
  cookie_signing_key = "HEREISA32CHARSECRETWHICHISMADEUP"
  debug = true
  enable_user_signup = true
  minimum_password_length = 8
  minimum_username_length = 4
  secure_cookies_only = false

[database]
  connection_details = "postgres://dbuser:hunter2@database:5432/todo?sslmode=disable"
  debug = true
  provider = "postgres"
  run_migrations = true

[frontend]
  cache_static_files = false
  debug = true
  static_files_directory = "/frontend"

[meta]
  run_mode = "development"
  startup_deadline = "1m0s"

[metrics]
  database_metrics_collection_interval = "1s"
  metrics_provider = "prometheus"
  runtime_metrics_collection_interval = "1s"
  tracing_provider = "jaeger"

[search]
  items_index_path = "items.bleve"

[server]
  debug = true
  http_port = 8888

[webhooks]
  enabled = false
