
[audit_log]
  enabled = true

[auth]
  debug = true
  enable_user_signup = true
  minimum_password_length = 8
  minimum_username_length = 4

  [auth.cookies]
    domain = "localhost"
    hash_key = "HEREISA32CHARSECRETWHICHISMADEUP"
    lifetime = "24h0m0s"
    name = "todocookie"
    secure_only = false
    signing_key = "HEREISA32CHARSECRETWHICHISMADEUP"

  [auth.paseto]
    issuer = "todo_service"
    lifetime = "1m0s"
    local_mode_key = [144, 87, 11, 199, 129, 98, 133, 136, 28, 189, 132, 105, 27, 83, 153, 191, 107, 91, 220, 226, 140, 251, 241, 37, 49, 58, 52, 242, 181, 9, 148, 210]

[capitalism]
  enabled = true
  provider = "stripe"

  [capitalism.stripe]
    api_key = "sk_test_51IrCfgJ45Mr1esdKpPc3lI5Si9USkxqBEyebZkc9ypJY5S87F76QeE2Tgg3PvzyPZQVchlDVc7fOsPLOM698e2Dc00wY1BKUdO"
    cancel_url = "http://localhost:8888/billing/checkout/cancel"
    success_url = "http://localhost:8888/billing/checkout/success"
    webhook_secret = "whsec_L9XCRWzqyl8x7mNg4W0VihURRco9wzGK"

[database]
  connection_details = "postgres://dbuser:hunter2@database:5432/todo?sslmode=disable"
  debug = true
  max_ping_attempts = 50
  metrics_collection_interval = "1s"
  provider = "postgres"
  run_migrations = true

[encoding]
  content_type = "application/json"

[frontend]
  use_fake_data = false

[meta]
  debug = false
  run_mode = "development"

[observability]

  [observability.metrics]
    provider = "prometheus"
    runtime_metrics_collection_interval = "1s"

  [observability.tracing]
    provider = ""
    span_collection_probability = 1.0

[search]
  items_index_path = "items.bleve"
  provider = "bleve"

[server]
  debug = true
  http_port = 8888
  startup_deadline = "1m0s"

[uploads]

  [uploads.storage_config]
    bucket_name = "avatars"
    debug = true
    provider = "memory"
    upload_filename_key = "avatar"

[webhooks]
  enabled = false
