
[audit_log]
  enabled = true

[auth]
  cookie_domain = "localhost"
  cookie_lifetime = "24h0m0s"
  cookie_name = "todocookie"
  cookie_signing_key = "HEREISA32CHARSECRETWHICHISMADEUP"
  debug = true
  enable_user_signup = true
  minimum_password_length = 8
  minimum_username_length = 4
  secure_cookies_only = false

[database]
  connection_details = "postgres://dbuser:hunter2@database:5432/todo?sslmode=disable"
  debug = true
  max_ping_attempts = 0
  metrics_collection_interval = "1s"
  provider = "postgres"
  run_migrations = true

[frontend]
  cache_static_files = false
  debug = true
  static_files_directory = "/frontend"

[meta]
  debug = false
  run_mode = "development"

[observability]
  runtime_metrics_collection_interval = "1s"

  [observability.metrics]
    provider = "prometheus"

  [observability.tracing]
    provider = "jaeger"
    span_collection_probability = 1.0

[search]
  items_index_path = "items.bleve"
  provider = "bleve"

[server]
  debug = true
  http_port = 8888
  startup_deadline = "1m0s"

[uploads]

  [uploads.storage_config]
    bucket_name = "avatars"
    debug = true
    provider = "filesystem"
    upload_filename = ""

    [uploads.storage_config.filesystem]
      root_directory = "artifacts"

[webhooks]
  enabled = false
