
[audit_log]
  enabled = true

[auth]
  debug = true
  enable_user_signup = true
  minimum_password_length = 8
  minimum_username_length = 4

  [auth.cookies]
    domain = "localhost"
    lifetime = "24h0m0s"
    name = "todocookie"
    secure_only = false
    signing_key = "HEREISA32CHARSECRETWHICHISMADEUP"

  [auth.paseto]
    issuer = "todo_service"
    lifetime = "1m0s"
    local_mode_key = [75,207,180,79,192,38,171,112,148,215,191,0,230,109,193,149,242,152,92,23,70,23,49,228,155,107,24,203,148,106,70,86]

[database]
  connection_details = "postgres://dbuser:hunter2@database:5432/todo?sslmode=disable"
  debug = true
  max_ping_attempts = 50
  metrics_collection_interval = "1s"
  provider = "postgres"
  run_migrations = true

[encoding]
  content_type = "application/json"

[frontend]
  cache_static_files = false
  debug = false
  static_files_directory = "/frontend"

[meta]
  debug = false
  run_mode = "development"

[observability]

  [observability.metrics]
    provider = "prometheus"
    runtime_metrics_collection_interval = "1s"

  [observability.tracing]
    provider = ""
    span_collection_probability = 1.0

[search]
  items_index_path = "items.bleve"
  provider = "bleve"

[server]
  debug = true
  http_port = 8888
  startup_deadline = "1m0s"

[uploads]

  [uploads.storage_config]
    bucket_name = "avatars"
    debug = true
    provider = "memory"
    upload_filename_key = "avatar"

[webhooks]
  enabled = false
