
[audit_log]
  enabled = true

[auth]
  debug = false
  enable_user_signup = true
  minimum_password_length = 8
  minimum_username_length = 4

  [auth.cookies]
    domain = "localhost"
    lifetime = "24h0m0s"
    name = "todocookie"
    secure_only = false
    signing_key = "HEREISA32CHARSECRETWHICHISMADEUP"

  [auth.paseto]
    issuer = "todo_service"
    lifetime = "1m0s"
    local_mode_key = [122,165,98,115,121,48,57,2,134,80,230,186,114,43,215,65,101,109,229,58,173,166,113,56,209,113,97,68,177,147,173,173]

[database]
  connection_details = "postgres://dbuser:hunter2@database:5432/todo?sslmode=disable"
  debug = false
  max_ping_attempts = 50
  metrics_collection_interval = "2s"
  provider = "postgres"
  run_migrations = true

  [database.create_test_user]
    hashed_password = "$2a$11$EiHpH3NCUjo1EHvcuRJM7uBxY68BbjyA2ErI4twEWjkIvTX6cfSNi"
    is_site_admin = true
    password = "integration-tests-are-cool"
    username = "exampleUser"

[frontend]
  cache_static_files = false
  debug = false
  static_files_directory = "/frontend"

[meta]
  debug = false
  run_mode = "testing"

[observability]
  runtime_metrics_collection_interval = "1s"

  [observability.metrics]
    provider = ""

  [observability.tracing]
    provider = "jaeger"
    span_collection_probability = 1.0

    [observability.tracing.jaeger]
      collector_endpoint = "http://tracing-server:14268/api/traces"
      service_name = "todo-service"

[search]
  items_index_path = "items.bleve"
  provider = "bleve"

[server]
  debug = false
  http_port = 8888
  startup_deadline = "1m0s"

[uploads]

  [uploads.storage_config]
    bucket_name = "avatars"
    debug = false
    provider = "memory"
    upload_filename_key = ""

[webhooks]
  enabled = false
