
[audit_log]
  enabled = true

[auth]
  debug = false
  enable_user_signup = true
  minimum_password_length = 8
  minimum_username_length = 4

  [auth.cookies]
    domain = "localhost"
    hash_key = ""
    lifetime = "24h0m0s"
    name = "todocookie"
    secure_only = false
    signing_key = "HEREISA32CHARSECRETWHICHISMADEUP"

  [auth.paseto]
    issuer = "todo_service"
    lifetime = "1m0s"
    local_mode_key = [144, 87, 11, 199, 129, 98, 133, 136, 28, 189, 132, 105, 27, 83, 153, 191, 107, 91, 220, 226, 140, 251, 241, 37, 49, 58, 52, 242, 181, 9, 148, 210]

[capitalism]
  enabled = true
  provider = "stripe"

  [capitalism.stripe]
    api_key = "sk_test_51IrCfgJ45Mr1esdKpPc3lI5Si9USkxqBEyebZkc9ypJY5S87F76QeE2Tgg3PvzyPZQVchlDVc7fOsPLOM698e2Dc00wY1BKUdO"
    cancel_url = "http://localhost:8888/billing/checkout/cancel"
    success_url = "http://localhost:8888/billing/checkout/success"
    webhook_secret = "whsec_L9XCRWzqyl8x7mNg4W0VihURRco9wzGK"

[database]
  connection_details = "dbuser:hunter2@tcp(database:3306)/todo"
  debug = false
  max_ping_attempts = 50
  metrics_collection_interval = "2s"
  provider = "mariadb"
  run_migrations = true

  [database.create_test_user]
    hashed_password = "$argon2id$v=19$m=65536,t=1,p=2$lIdR2k3mjHC1EHAGQDBaGw$c4uD8nlkgMedUOD18LhyLhhu9t61HwogQiQVKxXMt7g"
    is_site_admin = true
    password = "integration-tests-are-cool"
    username = "exampleUser"

[encoding]
  content_type = "application/json"

[frontend]
  use_fake_data = false

[meta]
  debug = false
  run_mode = "testing"

[observability]

  [observability.metrics]
    provider = ""
    runtime_metrics_collection_interval = "1s"

  [observability.tracing]
    provider = "jaeger"
    span_collection_probability = 1.0

    [observability.tracing.jaeger]
      collector_endpoint = "http://tracing-server:14268/api/traces"
      service_name = "todo-service"

[search]
  items_index_path = "items.bleve"
  provider = "bleve"

[server]
  debug = false
  http_port = 8888
  startup_deadline = "5m0s"

[uploads]

  [uploads.storage_config]
    bucket_name = "avatars"
    debug = false
    provider = "memory"
    upload_filename_key = ""

[webhooks]
  enabled = false
