
[audit_log]
  enabled = true

[auth]
  cookie_domain = "localhost"
  cookie_lifetime = "24h0m0s"
  cookie_name = "todocookie"
  cookie_signing_key = "HEREISA32CHARSECRETWHICHISMADEUP"
  debug = false
  enable_user_signup = true
  minimum_password_length = 8
  minimum_username_length = 4
  secure_cookies_only = false

[database]
  connection_details = "postgres://dbuser:hunter2@database:5432/todo?sslmode=disable"
  debug = false
  metrics_collection_interval = "2s"
  provider = "postgres"
  run_migrations = true

  [database.create_test_user]
    hashed_password = "$2a$11$g6kwPpBxPQM.WB1SOIZ1r.p2Fu/fs9biFmyx/Tz/0VzVZAE4eAVrG"
    is_admin = true
    password = "integration-tests-are-cool"
    username = "exampleUser"

[frontend]
  cache_static_files = false
  debug = false
  static_files_directory = "/frontend"

[meta]
  debug = false
  run_mode = "testing"

[observability]
  runtime_metrics_collection_interval = "1s"

  [observability.metrics]
    provider = ""

  [observability.tracing]
    provider = ""

[search]
  items_index_path = "items.bleve"
  provider = "bleve"

[server]
  debug = false
  http_port = 8888
  startup_deadline = "1m0s"

[uploads]

  [uploads.storage_config]
    debug = false
    name = "avatars"
    provider = "filesystem"

    [uploads.storage_config.filesystem]
      root_directory = "artifacts"

[webhooks]
  enabled = false
