
[audit_log]
  enabled = true

[auth]
  debug = false
  enable_user_signup = true
  minimum_password_length = 8
  minimum_username_length = 4

  [auth.cookies]
    domain = "localhost"
    lifetime = "24h0m0s"
    name = "todocookie"
    secure_only = false
    signing_key = "HEREISA32CHARSECRETWHICHISMADEUP"

  [auth.paseto]
    issuer = "todo_service"
    lifetime = "1m0s"
    local_mode_key = [221,103,7,252,19,165,191,101,151,132,147,253,57,236,232,102,141,3,126,139,146,58,135,84,38,62,109,227,169,18,71,189]

[database]
  connection_details = "postgres://dbuser:hunter2@database:5432/todo?sslmode=disable"
  debug = false
  max_ping_attempts = 50
  metrics_collection_interval = "2s"
  provider = "postgres"
  run_migrations = true

  [database.create_test_user]
    hashed_password = "$2a$11$OHvJbYHQustzX32snwegSu4L.5aeuLVVMoOVCrV8UlFe/oXm/wcqy"
    is_site_admin = true
    password = "integration-tests-are-cool"
    username = "exampleUser"

[frontend]
  cache_static_files = false
  debug = false
  static_files_directory = "/frontend"

[meta]
  debug = false
  run_mode = "testing"

[observability]
  runtime_metrics_collection_interval = "1s"

  [observability.metrics]
    provider = ""

  [observability.tracing]
    provider = ""
    span_collection_probability = 1.0

[search]
  items_index_path = "items.bleve"
  provider = "bleve"

[server]
  debug = false
  http_port = 8888
  startup_deadline = "1m0s"

[uploads]

  [uploads.storage_config]
    bucket_name = "avatars"
    debug = false
    provider = "filesystem"
    upload_filename = ""

    [uploads.storage_config.filesystem]
      root_directory = "artifacts"

[webhooks]
  enabled = false
