
[audit_log]
  enabled = true

[auth]
  debug = false
  enable_user_signup = true
  minimum_password_length = 8
  minimum_username_length = 4

  [auth.cookies]
    domain = "localhost"
    hash_key = ""
    lifetime = "24h0m0s"
    name = "todocookie"
    secure_only = false
    signing_key = "HEREISA32CHARSECRETWHICHISMADEUP"

  [auth.paseto]
    issuer = "todo_service"
    lifetime = "1m0s"
    local_mode_key = [1, 76, 237, 107, 42, 182, 114, 61, 107, 22, 46, 87, 255, 16, 194, 174, 81, 226, 249, 4, 243, 178, 16, 58, 168, 126, 237, 67, 85, 29, 73, 142]

[capitalism]
  enabled = false
  provider = ""

[database]
  connection_details = "postgres://dbuser:hunter2@database:5432/todo?sslmode=disable"
  debug = false
  max_ping_attempts = 50
  metrics_collection_interval = "2s"
  provider = "postgres"
  run_migrations = true

  [database.create_test_user]
    hashed_password = "$argon2id$v=19$m=65536,t=1,p=2$nx0cZaaSddJPmuwvWCF6yA$hOBs2S93Lsdx0jHh9CAYZt8X7t2Qs5c9t/n3yg+JImE"
    is_site_admin = true
    password = "integration-tests-are-cool"
    username = "exampleUser"

[encoding]
  content_type = "application/json"

[frontend]
  use_fake_data = false

[meta]
  debug = false
  run_mode = "testing"

[observability]

  [observability.metrics]
    provider = ""
    runtime_metrics_collection_interval = "1s"

  [observability.tracing]
    provider = "jaeger"
    span_collection_probability = 1.0

    [observability.tracing.jaeger]
      collector_endpoint = "http://tracing-server:14268/api/traces"
      service_name = "todo-service"

[search]
  items_index_path = "items.bleve"
  provider = "bleve"

[server]
  debug = false
  http_port = 8888
  startup_deadline = "1m0s"

[uploads]

  [uploads.storage_config]
    bucket_name = "avatars"
    debug = false
    provider = "memory"
    upload_filename_key = ""

[webhooks]
  enabled = false
