
[audit_log]
  enabled = true

[auth]
  cookie_domain = "localhost"
  cookie_lifetime = "24h0m0s"
  cookie_name = "todocookie"
  cookie_signing_key = "HEREISA32CHARSECRETWHICHISMADEUP"
  debug = false
  enable_user_signup = true
  minimum_password_length = 8
  minimum_username_length = 4
  secure_cookies_only = false

[database]
  connection_details = "dbuser:hunter2@tcp(database:3306)/todo"
  debug = false
  max_ping_attempts = 50
  metrics_collection_interval = "2s"
  provider = "mariadb"
  run_migrations = true

  [database.create_test_user]
    hashed_password = "$2a$11$/Ke38VVQu2nZCQ.C0N8whOgso2LwDlYloBbkvY2jbt1UQLI0yj3qS"
    is_site_admin = true
    password = "integration-tests-are-cool"
    username = "exampleUser"

[frontend]
  cache_static_files = false
  debug = false
  static_files_directory = "/frontend"

[meta]
  debug = false
  run_mode = "testing"

[observability]
  runtime_metrics_collection_interval = "1s"

  [observability.metrics]
    provider = ""

  [observability.tracing]
    provider = ""
    span_collection_probability = 1.0

[search]
  items_index_path = "items.bleve"
  provider = "bleve"

[server]
  debug = false
  http_port = 8888
  startup_deadline = "5m0s"

[uploads]

  [uploads.storage_config]
    bucket_name = "avatars"
    debug = false
    provider = "filesystem"
    upload_filename = ""

    [uploads.storage_config.filesystem]
      root_directory = "artifacts"

[webhooks]
  enabled = false
