
[auth]
  cookie_lifetime = "24h0m0s"
  cookie_secret = "HEREISA32CHARSECRETWHICHISMADEUP"
  enable_user_signup = true

[database]
  connection_details = "/tmp/db"
  create_test_user = false
  debug = false
  provider = "sqlite"

[frontend]
  static_files_directory = "/frontend"

[meta]
  debug = false
  run_mode = "testing"
  startup_deadline = "1m0s"

[metrics]
  database_metrics_collection_interval = "2s"
  metrics_provider = "prometheus"
  runtime_metrics_collection_interval = "2s"
  tracing_provider = "jaeger"

[search]
  items_index_path = "items.bleve"

[server]
  debug = true
  http_port = 8888
