
[audit_log]
  enabled = true

[auth]
  debug = false
  enable_user_signup = true
  minimum_password_length = 8
  minimum_username_length = 4

  [auth.cookies]
    domain = "localhost"
    lifetime = "24h0m0s"
    name = "todocookie"
    secure_only = false
    signing_key = "HEREISA32CHARSECRETWHICHISMADEUP"

  [auth.paseto]
    issuer = "todo_service"
    lifetime = "1m0s"
    local_mode_key = [253, 200, 209, 84, 103, 40, 130, 240, 222, 88, 12, 35, 210, 122, 127, 130, 96, 100, 91, 154, 231, 196, 227, 60, 251, 175, 1, 2, 177, 136, 220, 239]

[database]
  connection_details = "postgres://dbuser:hunter2@database:5432/todo?sslmode=disable"
  debug = false
  max_ping_attempts = 50
  metrics_collection_interval = "2s"
  provider = "postgres"
  run_migrations = true

  [database.create_test_user]
    hashed_password = "$argon2id$v=19$m=65536,t=1,p=2$1UqsjxmyQs65Rvktalc3Jw$XpuLTc2cG3uRHnDZ4tItNbLbsDJ3Bdmfk1ezcr7dl+w"
    is_site_admin = true
    password = "integration-tests-are-cool"
    username = "exampleUser"

[encoding]
  content_type = "application/json"

[frontend]
  use_fake_data = false

[meta]
  debug = false
  run_mode = "testing"

[observability]

  [observability.metrics]
    provider = ""
    runtime_metrics_collection_interval = "1s"

  [observability.tracing]
    provider = "jaeger"
    span_collection_probability = 1.0

    [observability.tracing.jaeger]
      collector_endpoint = "http://tracing-server:14268/api/traces"
      service_name = "todo-service"

[search]
  items_index_path = "items.bleve"
  provider = "bleve"

[server]
  debug = false
  http_port = 8888
  startup_deadline = "1m0s"

[uploads]

  [uploads.storage_config]
    bucket_name = "avatars"
    debug = false
    provider = "memory"
    upload_filename_key = ""

[webhooks]
  enabled = false
