
[audit_log]
  enabled = true

[auth]
  debug = false
  enable_user_signup = true
  minimum_password_length = 8
  minimum_username_length = 4

  [auth.cookies]
    domain = "localhost"
    lifetime = "24h0m0s"
    name = "todocookie"
    secure_only = false
    signing_key = "HEREISA32CHARSECRETWHICHISMADEUP"

  [auth.paseto]
    issuer = "todo_service"
    lifetime = "1m0s"
    local_mode_key = [73,214,56,181,185,31,67,103,20,208,22,205,182,197,20,160,135,104,88,43,137,157,219,246,169,111,85,230,38,108,28,73]

[database]
  connection_details = "dbuser:hunter2@tcp(database:3306)/todo"
  debug = false
  max_ping_attempts = 50
  metrics_collection_interval = "2s"
  provider = "mariadb"
  run_migrations = true

  [database.create_test_user]
    hashed_password = "$2a$11$aysVVqJPNoN/TJ0fS3WJ7Oqh1LbVbm/UeWEhfTt/ogj8Pd5LZEnt."
    is_site_admin = true
    password = "integration-tests-are-cool"
    username = "exampleUser"

[frontend]
  cache_static_files = false
  debug = false
  static_files_directory = "/frontend"

[meta]
  debug = false
  run_mode = "testing"

[observability]
  runtime_metrics_collection_interval = "1s"

  [observability.metrics]
    provider = ""

  [observability.tracing]
    provider = "jaeger"
    span_collection_probability = 1.0

    [observability.tracing.jaeger]
      collector_endpoint = "http://tracing-server:14268/api/traces"
      service_name = "todo-service"

[search]
  items_index_path = "items.bleve"
  provider = "bleve"

[server]
  debug = false
  http_port = 8888
  startup_deadline = "5m0s"

[uploads]

  [uploads.storage_config]
    bucket_name = "avatars"
    debug = false
    provider = "memory"
    upload_filename = ""

[webhooks]
  enabled = false
