
[audit_log]
  enabled = true

[auth]
  cookie_domain = "localhost"
  cookie_lifetime = "24h0m0s"
  cookie_signing_key = "HEREISA32CHARSECRETWHICHISMADEUP"
  enable_user_signup = true
  minimum_password_length = 8
  minimum_username_length = 4

[database]
  connection_details = "/tmp/db"
  debug = false
  provider = "sqlite"
  run_migrations = true

  [database.create_test_user]
    is_admin = true
    password = "integration-tests-are-cool"
    username = "exampleUser"

[frontend]
  static_files_directory = "/frontend"

[meta]
  debug = false
  run_mode = "testing"
  startup_deadline = "1m0s"

[metrics]
  database_metrics_collection_interval = "2s"
  metrics_provider = "prometheus"
  runtime_metrics_collection_interval = "2s"
  tracing_provider = "jaeger"

[search]
  items_index_path = "items.bleve"

[server]
  debug = false
  http_port = 8888

[webhooks]
  enabled = false
