version: '3.3'
services:
    todo-server:
        environment:
            CONFIGURATION_FILEPATH: '/etc/config.toml'
            JAEGER_AGENT_HOST: 'tracing-server'
            JAEGER_AGENT_PORT: '6831'
            JAEGER_SAMPLER_MANAGER_HOST_PORT: 'tracing-server:5778'
            JAEGER_SERVICE_NAME: 'todo-server'
            # USE_NOOP_LOGGER: 'true'
        ports:
            - 80:8888
        build:
            context: '../../../../'
            dockerfile: 'environments/testing/dockerfiles/integration-server-sqlite.Dockerfile'
    test:
        environment:
            TARGET_ADDRESS: 'http://todo-server:8888'
            DB_VENDOR: 'sqlite'
        links:
            - todo-server
        build:
            context: '../../../../'
            dockerfile: 'environments/testing/dockerfiles/integration-tests.Dockerfile'
        container_name: 'sqlite_integration_tests'
