version: "3.8"
services:
    workers:
        build:
            context: '../../../../'
            dockerfile: 'environments/testing/dockerfiles/workers.Dockerfile'
        environment:
            CONFIGURATION_FILEPATH: '/etc/service.config'
            TODO_WORKERS_LOCAL_CONFIG_STORE_KEY: 'SUFNQVdBUkVUSEFUVEhJU1NFQ1JFVElTVU5TRUNVUkU='
        volumes:
            - source: '../../../../environments/testing/config_files/integration-tests-postgres.config'
              target: '/etc/service.config'
              type: 'bind'
    api_server:
        depends_on:
            - workers
        environment:
            USE_NOOP_LOGGER: 'nope'
            TODO_SERVER_LOCAL_CONFIG_STORE_KEY: 'SUFNQVdBUkVUSEFUVEhJU1NFQ1JFVElTVU5TRUNVUkU='
            CONFIGURATION_FILEPATH: '/etc/service.config'
        ports:
            - '8888:8888'
        build:
            context: '../../../../'
            dockerfile: 'environments/testing/dockerfiles/integration-server.Dockerfile'
        volumes:
            - source: '../../../../environments/testing/config_files/integration-tests-postgres.config'
              target: '/etc/service.config'
              type: 'bind'
