version: "3.3"
services:
    database:
        image: postgres:13
        environment:
            POSTGRES_DB: 'todo'
            POSTGRES_PASSWORD: 'hunter2'
            POSTGRES_USER: 'dbuser'
        logging:
            driver: none
        ports:
            - 2345:5432
    workers:
        container_name: workers
        depends_on:
            - todo-server
        links:
            - worker_queue
            - tracing-server
            - database
        build:
            context: '../../../../'
            dockerfile: 'environments/testing/dockerfiles/workers.Dockerfile'
        environment:
            CONFIGURATION_FILEPATH: '/etc/service.config'
            TODO_WORKERS_LOCAL_CONFIG_STORE_KEY: 'SUFNQVdBUkVUSEFUVEhJU1NFQ1JFVElTVU5TRUNVUkU='
        volumes:
            - source: '../../../../environments/testing/config_files/integration-tests-postgres.config'
              target: '/etc/service.config'
              type: 'bind'
    todo-server:
        environment:
            TODO_SERVICE_LOCAL_CONFIG_STORE_KEY: 'SUFNQVdBUkVUSEFUVEhJU1NFQ1JFVElTVU5TRUNVUkU='
            USE_NOOP_LOGGER: 'nope'
        links:
            - worker_queue
            - tracing-server
            - database
        volumes:
            - source: '../../../../environments/testing/config_files/integration-tests-postgres.config'
              target: '/etc/service.config'
              type: 'bind'
    test:
        container_name: 'postgres_integration_tests'
