version: '3.3'
services:
    todo-server:
        environment:
            TODO_SERVICE_LOCAL_CONFIG_STORE_KEY: 'SUFNQVdBUkVUSEFUVEhJU1NFQ1JFVElTVU5TRUNVUkU='
            USE_NOOP_LOGGER: 'nope'
        volumes:
          - source: '../../../../environments/testing/config_files/integration-tests-sqlite.config'
            target: '/etc/service.config'
            type: 'bind'
          - source: '../../../../artifacts/database.sqlite'
            target: '/tmp/db'
            type: 'bind'
    test:
        container_name: 'sqlite_integration_tests'
    workers:
      container_name: workers
      depends_on:
        - todo-server
      links:
        - database
        - nsqlookupd
      build:
        context: '../../../../'
        dockerfile: 'environments/testing/dockerfiles/workers.Dockerfile'
      environment:
        CONFIGURATION_FILEPATH: '/etc/service.config'
        TODO_WORKERS_LOCAL_CONFIG_STORE_KEY: 'SUFNQVdBUkVUSEFUVEhJU1NFQ1JFVElTVU5TRUNVUkU='
      volumes:
        - source: '../../../../environments/testing/config_files/integration-tests-sqlite.config'
          target: '/etc/service.config'
          type: 'bind'