version: "3.3"
services:
    database:
        image: postgres:latest
        environment:
            POSTGRES_DB: 'todo'
            POSTGRES_PASSWORD: 'hunter2'
            POSTGRES_USER: 'dbuser'
        logging:
            driver: none
        ports:
            - 2345:5432
    todo-server:
        environment:
            CONFIGURATION_FILEPATH: '/etc/config.toml'
            JAEGER_AGENT_HOST: 'tracing-server'
            JAEGER_AGENT_PORT: '6831'
            JAEGER_SAMPLER_MANAGER_HOST_PORT: 'tracing-server:5778'
            JAEGER_SERVICE_NAME: 'todo-server'
        ports:
            - 80:8888
        links:
            - database
        logging:
            driver: none
        build:
            context: '../../../../'
            dockerfile: 'environments/testing/dockerfiles/integration-server-postgres.Dockerfile'
    test:
        environment:
            TARGET_ADDRESS: 'http://todo-server:8888'
            DB_ADDRESS: 'postgres://dbuser:hunter2@database:5432/todo?sslmode=disable'
            DB_VENDOR: 'postgres'
        links:
            - todo-server
        build:
            context: '../../../../'
            dockerfile: 'environments/testing/dockerfiles/integration-tests.Dockerfile'
        container_name: 'postgres_integration_tests'
    tracing-server:
        image: jaegertracing/all-in-one:latest
        logging:
            driver: none
        ports:
            - 6831:6831/udp
            - 5778:5778
            - 16686:16686