version: "3.3"
services:
    database:
        image: "mariadb:latest"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
            MYSQL_DATABASE: 'todo'
            MYSQL_PASSWORD: 'hunter2'
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_USER: 'dbuser'
        logging:
            driver: none
        ports:
            - 3306:3306
    todo-server:
        links:
            - database
        environment:
            USE_NOOP_LOGGER: 'nope'
        volumes:
            - source: '../../../../environments/testing/config_files/integration-tests-mariadb.toml'
              target: '/etc/config.toml'
              type: 'bind'
    test:
        container_name: 'mariadb_integration_tests'