version: "3.3"
services:
    database:
        image: postgres:latest
        environment:
            POSTGRES_DB: 'todo'
            POSTGRES_PASSWORD: 'hunter2'
            POSTGRES_USER: 'dbuser'
        logging:
            driver: none
        ports:
            - 2345:5432
    todo-server:
        links:
            - database
            - tracing-server
            - prometheus
            - loki
            - promtail
        volumes:
            - source: '../../../../environments/testing/config_files/integration-tests-postgres.toml'
              target: '/etc/config.toml'
              type: 'bind'
    test:
        environment:
            TARGET_ADDRESS: 'http://todo-server:8888'
            DB_ADDRESS: 'postgres://dbuser:hunter2@database:5432/todo?sslmode=disable'
            DB_VENDOR: 'postgres'
        container_name: 'postgres_integration_tests'
