version: "3.8"
services:
    workers:
        container_name: workers
        depends_on:
            - todo-server
        build:
            context: '../../../../'
            dockerfile: 'environments/testing/dockerfiles/workers.Dockerfile'
        environment:
            CONFIGURATION_FILEPATH: '/etc/service.config'
            TODO_WORKERS_LOCAL_CONFIG_STORE_KEY: 'SUFNQVdBUkVUSEFUVEhJU1NFQ1JFVElTVU5TRUNVUkU='
        volumes:
            - source: '../../../../environments/testing/config_files/integration-tests-mysql.config'
              target: '/etc/service.config'
              type: 'bind'
    todo-server:
        container_name: api_server
        environment:
            TODO_SERVER_LOCAL_CONFIG_STORE_KEY: 'SUFNQVdBUkVUSEFUVEhJU1NFQ1JFVElTVU5TRUNVUkU='
            CONFIGURATION_FILEPATH: '/etc/service.config'
            JAEGER_DISABLED: 'false'
        ports:
            - '8888:8888'
        build:
            context: '../../../../'
            dockerfile: 'environments/testing/dockerfiles/integration-server.Dockerfile'
        volumes:
            - source: '../../../../environments/testing/config_files/integration-tests-mysql.config'
              target: '/etc/service.config'
              type: 'bind'
