version: '3.3'

services:
  todo-server:
    build:
      context: ../
      dockerfile: dockerfiles/development.Dockerfile
    ports:
      - '80:8888'
    environment:
      DOCKER: 'true'
      JAEGER_SERVICE_NAME: 'todo-server'
      JAEGER_AGENT_HOST: 'tracing-server'
      JAEGER_AGENT_PORT: '6831'
      JAEGER_SAMPLER_MANAGER_HOST_PORT: 'tracing-server:5778'
    volumes:
      - type: bind
        source: ../frontend/v1/public
        target: /frontend
    links:
      - tracing-server
      - database
    depends_on:
      - prometheus
      - grafana
    # logging:
    #   driver: none

  database:
    image: postgres:latest
    ports:
      - '2345:5432'
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: hunter2
    logging:
      driver: none

  tracing-server:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 5778:5778
      - 16686:16686
    logging:
      driver: none

  prometheus:
    image: quay.io/prometheus/prometheus:v2.0.0
    volumes:
      - type: bind
        source: ../deploy/prometheus/local/config.yaml
        target: /etc/prometheus/config.yaml
    command:
      '--config.file=/etc/prometheus/config.yaml --storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    logging:
      driver: none

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ../deploy/grafana/local/provisioning
        target: /etc/grafana/provisioning
      - type: bind
        source: ../deploy/grafana/dashboards
        target: /etc/grafana/dashboards
    links:
      - prometheus
    logging:
      driver: none
