version: '3.3'

services:
    tracing-server:
        image: jaegertracing/all-in-one:latest
        ports:
            - 6831:6831/udp
            - 5778:5778
            - 16686:16686

    server:
        build:
            context: ../
            dockerfile: dockerfiles/server.Dockerfile
        ports:
            - '443:443'
        environment:
            DOCKER: 'true'
            JAEGER_SERVICE_NAME: 'todo-server'
            JAEGER_AGENT_HOST: 'tracing-server'
            JAEGER_AGENT_PORT: '6831'
            JAEGER_SAMPLER_MANAGER_HOST_PORT: 'tracing-server:5778'
        links:
            - tracing-server
        # logging:
        #     driver: none

