version: '3.3'

services:
  tracing-server:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 5778:5778
      - 16686:16686

  database:
    image: postgres:latest
    ports:
      - '2345:5432'
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: hunter2

  todo-server:
    build:
      context: ../
      dockerfile: dockerfiles/server.Dockerfile
    ports:
      - '443:443'
    environment:
      DOCKER: 'true'
      JAEGER_SERVICE_NAME: 'todo-server'
      JAEGER_AGENT_HOST: 'tracing-server'
      JAEGER_AGENT_PORT: '6831'
      JAEGER_SAMPLER_MANAGER_HOST_PORT: 'tracing-server:5778'
    links:
      - database
      - grafana
      - tracing-server
    logging:
      driver: none

  metrics-exporter:
    image: prom/node-exporter:latest
    ports:
      - 9100:9100
    # network_mode: host

  prometheus:
    image: quay.io/prometheus/prometheus:v2.0.0
    volumes:
      - type: bind
        source: ./deploy/prometheus/config.yaml
        target: /etc/prometheus/config.yaml
    command:
      '--config.file=/etc/prometheus/config.yaml --storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    depends_on:
      - metrics-exporter

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
