version: '3.3'

services:
    demo-server:
        build:
            context: ../
            dockerfile: dockerfiles/server.Dockerfile
        ports:
            - '1443:443'
        logging:
            driver: none

    integration-test:
        build:
            context: ../
            dockerfile: dockerfiles/integration-tests.Dockerfile
        links:
            - demo-server
