version: '3.3'

services:
  coverage-server:
    build:
      context: ../
      dockerfile: dockerfiles/integration-coverage-server.Dockerfile
    ports:
      - '80:8888'
    environment:
      DOCKER: 'true'
      RUNTIME_DURATION: '30s'
      CONFIGURATION_FILEPATH: 'config_files/coverage.toml'
    volumes:
      - ../artifacts/:/home/
    links:
      - database
    # logging:
    #   driver: none

  test:
    build:
      context: ../
      dockerfile: dockerfiles/integration-tests.Dockerfile
    environment:
      TARGET_ADDRESS: 'http://coverage-server'
      DOCKER: 'true'
      JAEGER_SERVICE_NAME: 'coverage-server'
      JAEGER_AGENT_HOST: 'tracing-server'
      JAEGER_AGENT_PORT: '6831'
      JAEGER_SAMPLER_MANAGER_HOST_PORT: 'tracing-server:5778'
      WAIT_FOR_COVERAGE: 'yes'
    links:
      - coverage-server
    # logging:
    #   driver: none

  database:
    image: postgres:latest
    ports:
      - '2345:5432'
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: hunter2
    volumes:
      - ../database/_postgres_init_.sql:/docker-entrypoint-initdb.d/10-init.sql
    logging:
      driver: none
