version: '3.3'

services:
  todo-server:
    build:
      context: ../
      dockerfile: dockerfiles/integration-server.Dockerfile
    ports:
      - '80:80'
      - '8888:8888'
    environment:
      DOCKER: 'true'
    links:
      - database
    # logging:
    #   driver: none

  test:
    build:
      context: ../
      dockerfile: dockerfiles/integration-tests.Dockerfile
    environment:
      DOCKER: 'true'
    links:
      - todo-server
    # logging:
    #   driver: none

  database:
    image: postgres:latest
    ports:
      - '2345:5432'
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: hunter2
    logging:
      driver: none
