version: '3.3'

services:
  todo-server:
    build:
      context: ../
      dockerfile: dockerfiles/integration-coverage.Dockerfile
    ports:
      - '80:80'
    environment:
      DOCKER: 'true'
      RUNTIME_DURATION: '5m'
    volumes:
      - ../artifacts/:/home/
    links:
      - database
    # logging:
    #   driver: none

  load-tests:
    build:
      context: ../
      dockerfile: dockerfiles/load-tests.Dockerfile
    environment:
      OAUTHLIB_INSECURE_TRANSPORT: 'true'
    links:
      - todo-server
    # logging:
    #   driver: none

  database:
    image: postgres:latest
    ports:
      - '2345:5432'
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: hunter2
      POSTGRES_DB: todo
    volumes:
      - ../database/_postgres_init_.sql:/docker-entrypoint-initdb.d/10-init.sql
    logging:
      driver: none
