version: '3.3'

services:
  todo-server:
    build:
      context: ../
      dockerfile: dockerfiles/integration-server.Dockerfile
    ports:
      - '80:80'
    environment:
      DOCKER: 'true'
    links:
      - database
    # logging:
    #   driver: none

  integration-test:
    build:
      context: ../
      dockerfile: dockerfiles/integration-tests-go.Dockerfile
    environment:
      DOCKER: 'true'
      DATABASE_TO_USE: 'postgres'
      JAEGER_SERVICE_NAME: 'todo-server'
      JAEGER_AGENT_HOST: 'tracing-server'
      JAEGER_AGENT_PORT: '6831'
      JAEGER_SAMPLER_MANAGER_HOST_PORT: 'tracing-server:5778'
    links:
      - todo-server
    # logging:
    #   driver: none

  database:
    image: postgres:latest
    ports:
      - '2345:5432'
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: hunter2
    volumes:
      - ../database/_postgres_init_.sql:/docker-entrypoint-initdb.d/10-init.sql
    logging:
      driver: none
