version: '3.3'

services:
    tracing-server:
      image: jaegertracing/all-in-one:latest
      ports:
        - 5775:5775/udp
        - 6831:6831/udp
        - 6832:6832/udp
        - 5778:5778
        - 16686:16686
        - 14268:14268
        - 9411:9411
      logging:
        driver: none

    database:
      image: postgres:latest
      ports:
        - "2345:5432"
      environment:
        POSTGRES_USER: todo
        POSTGRES_PASSWORD: hunter2
      logging:
        driver: none

    demo-server:
      build:
        context: ../
        dockerfile: dockerfiles/integration-server.Dockerfile
      ports:
        - '443:443'
      environment:
        DOCKER: 'true'
        JAEGER_SERVICE_NAME: 'todo-server'
        JAEGER_AGENT_HOST: 'tracing-server'
        JAEGER_AGENT_PORT: '6831'
        JAEGER_SAMPLER_MANAGER_HOST_PORT: 'tracing-server:5778'
      links:
        - database
        - tracing-server

    integration-test:
      build:
        context: ../
        dockerfile: dockerfiles/integration-tests.Dockerfile
      environment:
        DOCKER: 'true'
        JAEGER_SERVICE_NAME: 'todo-server'
        JAEGER_AGENT_HOST: 'tracing-server'
        JAEGER_AGENT_PORT: '6831'
        JAEGER_SAMPLER_MANAGER_HOST_PORT: 'tracing-server:5778'
      links:
        - database
        - tracing-server
        - demo-server
