version: '3.3'

services:
    demo-server:
        build:
            context: ../
            dockerfile: dockerfiles/integration-server.Dockerfile
        ports:
            - '443:443'
        environment:
            DOCKER: 'true'
        logging:
            driver: none

    integration-test:
        build:
            context: ../
            dockerfile: dockerfiles/integration-tests.Dockerfile
        environment:
            DOCKER: 'true'
        links:
            - demo-server
