version: "3.3"

services:
  todo-server:
    build:
      context: ../
      dockerfile: dockerfiles/integration-server.Dockerfile
    ports:
      - "80:8888"
    environment:
      DOCKER: "true"
      CONFIGURATION_FILEPATH: "config_files/integration-tests-mariadb.toml"
    links:
      - database
    depends_on:
      - database
    logging:
      driver: none

  load-tests:
    build:
      context: ../
      dockerfile: dockerfiles/load-tests.Dockerfile
    links:
      - todo-server
    environment:
      TARGET_ADDRESS: "http://todo-server:8888"
    logging:
      driver: none

  database:
    image: postgres:latest
    ports:
      - "2345:5432"
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: hunter2
    logging:
      driver: none
