version: '3.3'

services:
  tracing-server:
    image: jaegertracing/all-in-one:latest
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    logging:
      driver: none

  todo-server:
    build:
      context: ../
      dockerfile: dockerfiles/integration-server.Dockerfile
    ports:
      - '80:80'
    environment:
      DOCKER: 'true'
      JAEGER_SERVICE_NAME: 'todo-server'
      JAEGER_AGENT_HOST: 'tracing-server'
      JAEGER_AGENT_PORT: '6831'
      JAEGER_SAMPLER_MANAGER_HOST_PORT: 'tracing-server:5778'
    links:
      - tracing-server
      - prometheus
      - grafana

  load-tests:
    build:
      context: ../
      dockerfile: dockerfiles/load-tests.Dockerfile
    environment:
      DOCKER: 'true'
    links:
      - todo-server

  # locust-load-tests:
  #   image: grubykarol/locust
  #   environment:
  #     ATTACKED_HOST: http://todo-server
  #     LOCUST_FILE: /tests/locustfile.py
  #   ports:
  #     - 8089:8089
  #   links:
  #     - todo-server
  #   volumes:
  #     - ../tests/v1/locust:/tests

  prometheus:
    image: quay.io/prometheus/prometheus:v2.0.0
    volumes:
      - type: bind
        source: ../deploy/prometheus/local/config.yaml
        target: /etc/prometheus/config.yaml
    command:
      '--config.file=/etc/prometheus/config.yaml --storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    logging:
      driver: none

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ../deploy/grafana/local/provisioning
        target: /etc/grafana/provisioning
      - type: bind
        source: ../deploy/grafana/dashboards
        target: /etc/grafana/dashboards
    links:
      - prometheus
    logging:
      driver: none
