package permissions

import (
	"math"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestServiceAdminPermissions(t *testing.T) {
	t.Parallel()

	x := ServiceAdminPermission(math.MaxInt64)

	assert.True(t, x.CanCycleCookieSecrets())
	assert.True(t, x.CanBanUsers())
	assert.True(t, x.CanTerminateAccounts())
	assert.True(t, x.CanImpersonateAccounts())
	assert.True(t, x.hasUnusedServiceAdminPermission5())
	assert.True(t, x.hasUnusedServiceAdminPermission6())
	assert.True(t, x.hasUnusedServiceAdminPermission7())
	assert.True(t, x.hasUnusedServiceAdminPermission8())
	assert.True(t, x.hasUnusedServiceAdminPermission9())
	assert.True(t, x.hasUnusedServiceAdminPermission10())
	assert.True(t, x.hasUnusedServiceAdminPermission11())
	assert.True(t, x.hasUnusedServiceAdminPermission12())
	assert.True(t, x.hasUnusedServiceAdminPermission13())
	assert.True(t, x.hasUnusedServiceAdminPermission14())
	assert.True(t, x.hasUnusedServiceAdminPermission15())
	assert.True(t, x.hasUnusedServiceAdminPermission16())
	assert.True(t, x.hasUnusedServiceAdminPermission17())
	assert.True(t, x.hasUnusedServiceAdminPermission18())
	assert.True(t, x.hasUnusedServiceAdminPermission19())
	assert.True(t, x.hasUnusedServiceAdminPermission20())
	assert.True(t, x.hasUnusedServiceAdminPermission21())
	assert.True(t, x.hasUnusedServiceAdminPermission22())
	assert.True(t, x.hasUnusedServiceAdminPermission23())
	assert.True(t, x.hasUnusedServiceAdminPermission24())
	assert.True(t, x.hasUnusedServiceAdminPermission25())
	assert.True(t, x.hasUnusedServiceAdminPermission26())
	assert.True(t, x.hasUnusedServiceAdminPermission27())
	assert.True(t, x.hasUnusedServiceAdminPermission28())
	assert.True(t, x.hasUnusedServiceAdminPermission29())
	assert.True(t, x.hasUnusedServiceAdminPermission30())
	assert.True(t, x.hasUnusedServiceAdminPermission31())
	assert.True(t, x.hasUnusedServiceAdminPermission32())
	assert.True(t, x.hasUnusedServiceAdminPermission33())
	assert.True(t, x.hasUnusedServiceAdminPermission34())
	assert.True(t, x.hasUnusedServiceAdminPermission35())
	assert.True(t, x.hasUnusedServiceAdminPermission36())
	assert.True(t, x.hasUnusedServiceAdminPermission37())
	assert.True(t, x.hasUnusedServiceAdminPermission38())
	assert.True(t, x.hasUnusedServiceAdminPermission39())
	assert.True(t, x.hasUnusedServiceAdminPermission40())
	assert.True(t, x.hasUnusedServiceAdminPermission41())
	assert.True(t, x.hasUnusedServiceAdminPermission42())
	assert.True(t, x.hasUnusedServiceAdminPermission43())
	assert.True(t, x.hasUnusedServiceAdminPermission44())
	assert.True(t, x.hasUnusedServiceAdminPermission45())
	assert.True(t, x.hasUnusedServiceAdminPermission46())
	assert.True(t, x.hasUnusedServiceAdminPermission47())
	assert.True(t, x.hasUnusedServiceAdminPermission48())
	assert.True(t, x.hasUnusedServiceAdminPermission49())
	assert.True(t, x.hasUnusedServiceAdminPermission50())
	assert.True(t, x.hasUnusedServiceAdminPermission51())
	assert.True(t, x.hasUnusedServiceAdminPermission52())
	assert.True(t, x.hasUnusedServiceAdminPermission53())
	assert.True(t, x.hasUnusedServiceAdminPermission54())
	assert.True(t, x.hasUnusedServiceAdminPermission55())
	assert.True(t, x.hasUnusedServiceAdminPermission56())
	assert.True(t, x.hasUnusedServiceAdminPermission57())
	assert.True(t, x.hasUnusedServiceAdminPermission58())
	assert.True(t, x.hasUnusedServiceAdminPermission59())
	assert.True(t, x.hasUnusedServiceAdminPermission61())
	assert.True(t, x.hasUnusedServiceAdminPermission62())
	assert.True(t, x.hasUnusedServiceAdminPermission63())
	assert.True(t, x.hasUnusedServiceAdminPermission64())
}
