
[audit_log]
  enabled = true

[auth]
  debug = true
  enable_user_signup = true
  minimum_password_length = 8
  minimum_username_length = 4

  [auth.cookies]
    domain = "localhost"
    lifetime = "24h0m0s"
    name = "todocookie"
    secure_only = false
    signing_key = "HEREISA32CHARSECRETWHICHISMADEUP"

  [auth.paseto]
    issuer = "todo_service"
    lifetime = "5m0s"
    local_mode_key = [192,116,130,53,59,253,205,14,170,211,179,157,71,226,230,75,43,26,237,233,74,11,185,130,116,170,248,65,249,211,122,195]

[database]
  connection_details = "postgres://dbuser:hunter2@database:5432/todo?sslmode=disable"
  debug = true
  max_ping_attempts = 0
  metrics_collection_interval = "1s"
  provider = "postgres"
  run_migrations = true

  [database.create_test_user]
    hashed_password = "$2a$11$f22JSxUk9zSPmNhHvBLlB.7nU0y5IN8SOsuXIUdhRYqwKYdsoxxZ2"
    is_site_admin = true
    password = "authentication"
    username = "username"

[frontend]
  cache_static_files = false
  debug = true
  static_files_directory = "/frontend"

[meta]
  debug = true
  run_mode = "development"

[observability]
  runtime_metrics_collection_interval = "1s"

  [observability.metrics]
    provider = "prometheus"

  [observability.tracing]
    provider = "jaeger"
    span_collection_probability = 1.0

[search]
  items_index_path = "/search_indices/items.bleve"
  provider = "bleve"

[server]
  debug = true
  http_port = 8888
  startup_deadline = "1m0s"

[uploads]

  [uploads.storage_config]
    bucket_name = "avatars"
    debug = true
    provider = "filesystem"
    upload_filename = ""

    [uploads.storage_config.filesystem]
      root_directory = "artifacts"

[webhooks]
  enabled = false
