
[audit_log]
  enabled = true

[auth]
  debug = true
  enable_user_signup = true
  minimum_password_length = 8
  minimum_username_length = 4

  [auth.cookies]
    domain = "localhost"
    hash_key = "HEREISA32CHARSECRETWHICHISMADEUP"
    lifetime = "24h0m0s"
    name = "todocookie"
    secure_only = false
    signing_key = "HEREISA32CHARSECRETWHICHISMADEUP"

  [auth.paseto]
    issuer = "todo_service"
    lifetime = "1m0s"
    local_mode_key = [168, 144, 10, 187, 239, 108, 210, 93, 236, 211, 192, 167, 84, 245, 198, 102, 112, 198, 187, 229, 148, 123, 196, 199, 207, 49, 243, 98, 161, 210, 201, 71]

[database]
  connection_details = "postgres://dbuser:hunter2@database:5432/todo?sslmode=disable"
  debug = true
  max_ping_attempts = 50
  metrics_collection_interval = "1s"
  provider = "postgres"
  run_migrations = true

  [database.create_test_user]
    hashed_password = "$argon2id$v=19$m=65536,t=1,p=2$0YShZQ0Uqfd9H/drrrfcng$GRFsoMH/+3s/5Ht20UYSiBV6UgxczyeWNyU8Fk1hAkI"
    is_site_admin = true
    password = "password"
    username = "username"

[encoding]
  content_type = "application/json"

[frontend]
  use_fake_data = false

[meta]
  debug = true
  run_mode = "development"

[observability]

  [observability.metrics]
    provider = "prometheus"
    runtime_metrics_collection_interval = "1s"

  [observability.tracing]
    provider = "jaeger"
    span_collection_probability = 1.0

    [observability.tracing.jaeger]
      collector_endpoint = "http://tracing-server:14268/api/traces"
      service_name = "todo-service"

[search]
  items_index_path = "/search_indices/items.bleve"
  provider = "bleve"

[server]
  debug = true
  http_port = 8888
  startup_deadline = "1m0s"

[uploads]

  [uploads.storage_config]
    bucket_name = "avatars"
    debug = true
    provider = "filesystem"
    upload_filename_key = "avatar"

    [uploads.storage_config.filesystem]
      root_directory = "/avatars"

[webhooks]
  enabled = false
