
[audit_log]
  enabled = true

[auth]
  cookie_domain = "localhost"
  cookie_lifetime = "24h0m0s"
  cookie_name = "todocookie"
  cookie_signing_key = "HEREISA32CHARSECRETWHICHISMADEUP"
  debug = true
  enable_user_signup = true
  minimum_password_length = 8
  minimum_username_length = 4
  secure_cookies_only = false

[database]
  connection_details = "postgres://dbuser:hunter2@database:5432/todo?sslmode=disable"
  debug = true
  metrics_collection_interval = "1s"
  provider = "postgres"
  run_migrations = true

  [database.create_test_user]
    hashed_password = "$2a$11$DUhvI/ZcuEkUs0H35WQIR.gzvsWRwh4EuxoIs.Gr2inum5RLVELXe"
    is_admin = true
    password = "password"
    username = "username"

[frontend]
  cache_static_files = false
  debug = true
  static_files_directory = "/frontend"

[meta]
  debug = true
  run_mode = "development"

[observability]
  runtime_metrics_collection_interval = "1s"

  [observability.metrics]
    provider = "prometheus"

  [observability.tracing]
    provider = "jaeger"

[search]
  items_index_path = "/search_indices/items.bleve"
  provider = "bleve"

[server]
  debug = true
  http_port = 8888
  startup_deadline = "1m0s"

[uploads]

  [uploads.storage_config]
    debug = true
    name = "avatars"
    provider = "filesystem"

    [uploads.storage_config.filesystem]
      root_directory = "artifacts"

[webhooks]
  enabled = false
