version: "3.3"
services:
    database:
        image: postgres:latest
        environment:
            POSTGRES_DB: 'todo'
            POSTGRES_PASSWORD: 'hunter2'
            POSTGRES_USER: 'dbuser'
        logging:
            driver: none
        ports:
            - 2345:5432
    todo-server:
        environment:
            CONFIGURATION_FILEPATH: '/etc/config.toml'
            JAEGER_DISABLED: 'true'
        ports:
            - 80:8888
        links:
#            - tracing-server
            - database
            - prometheus
        volumes:
            - source: '../../frontend/dist'
              target: '/frontend'
              type: 'bind'
            - source: '../../artifacts/search_indices'
              target: '/search_indices'
              type: 'bind'
            - source: '../../environments/local/config.toml'
              target: '/etc/config.toml'
              type: 'bind'
        build:
            context: '../../'
            dockerfile: 'environments/local/Dockerfile'
    tracing-server:
        image: jaegertracing/all-in-one:1.22.0
        logging:
            driver: none
        ports:
            - "5775:5775/udp"
            - "6831:6831/udp"
            - "6832:6832/udp"
            - "5778:5778"
            - "16686:16686"
            - "14268:14268"
            - "9411:9411"
    prometheus:
        image: quay.io/prometheus/prometheus:v2.25.0
        command: '--config.file=/etc/prometheus/config.yaml --storage.tsdb.path=/prometheus --log.level=info'
        ports:
            - 9090:9090
        volumes:
            - source: "../../environments/local/prometheus/config.yaml"
              target: "/etc/prometheus/config.yaml"
              type: 'bind'
#    loki:
#      image: grafana/loki:1.6.0
#      ports:
#        - "3100:3100"
#      command: -config.file=/etc/loki/local-config.yaml
#      volumes:
#        - source: '../../environments/local/loki/config.yaml'
#          target: '/etc/loki/local-config.yaml'
#          type: 'bind'
#      links:
#        - grafana
#    promtail:
#      image: grafana/promtail:1.6.0
#      command: -config.file=/etc/promtail/config.yml
#      volumes:
#        - /var/log:/var/log
#        - source: '../../environments/local/promtail/config.yaml'
#          target: '/etc/promtail/config.yml'
#          type: 'bind'
#      links:
#        - loki
    grafana:
      image: grafana/grafana:7.4.3
      logging:
        driver: none
      ports:
        - 3000:3000
      links:
        - prometheus
      volumes:
        - source: '../../environments/local/grafana/grafana.ini'
          target: '/etc/grafana/grafana.ini'
          type: 'bind'
        - source: '../../environments/local/grafana/datasources.yaml'
          target: '/etc/grafana/provisioning/datasources/datasources.yml'
          type: 'bind'
        - source: '../../environments/local/grafana/dashboards.yaml'
          target: '/etc/grafana/provisioning/dashboards/dashboards.yml'
          type: 'bind'
        - source: '../../environments/local/grafana/dashboards'
          target: '/etc/grafana/provisioning/dashboards/dashboards'
          type: 'bind'