version: '3.3'
services:
    coverage-server:
        environment:
            CONFIGURATION_FILEPATH: 'config_files/coverage.toml'
            DOCKER: 'true'
            RUNTIME_DURATION: '30s'
        ports:
            - 80:8888
        links:
            - database
        volumes:
            - source: '../artifacts/'
              target: '/home/'
              type: 'bind'
        build:
            context: '../'
            dockerfile: 'dockerfiles/integration-coverage-server.Dockerfile'
    database:
        image: postgres:latest
        environment:
            POSTGRES_DB: 'todo'
            POSTGRES_PASSWORD: 'hunter2'
            POSTGRES_USER: 'dbuser'
        logging:
            driver: none
        ports:
            - 2345:5432
    test:
        environment:
            DOCKER: 'true'
            JAEGER_AGENT_HOST: 'tracing-server'
            JAEGER_AGENT_PORT: '6831'
            JAEGER_SAMPLER_MANAGER_HOST_PORT: 'tracing-server:5778'
            JAEGER_SERVICE_NAME: 'coverage-server'
            TARGET_ADDRESS: 'http://coverage-server'
            WAIT_FOR_COVERAGE: 'yes'
        links:
            - coverage-server
        build:
            context: '../'
            dockerfile: 'dockerfiles/integration-tests.Dockerfile'
