version: "3.3"
services:
    database:
        image: postgres:latest
        environment:
            POSTGRES_DB: 'todo'
            POSTGRES_PASSWORD: 'hunter2'
            POSTGRES_USER: 'dbuser'
        logging:
            driver: none
        ports:
            - 2345:5432
    todo-server:
        environment:
            CONFIGURATION_FILEPATH: 'config_files/integration-tests-postgres.toml'
            DOCKER: 'true'
        ports:
            - 80:8888
        links:
            - database
        build:
            context: '../'
            dockerfile: 'dockerfiles/integration-server.Dockerfile'
    test:
        environment:
            DOCKER: 'true'
            TARGET_ADDRESS: 'http://todo-server:8888'
        links:
            - todo-server
        build:
            context: '../'
            dockerfile: 'dockerfiles/integration-tests.Dockerfile'
        container_name: 'postgres_integration_tests'
