[meta]
# tracing_enabled = true
# debug = true

[server]
http_port = 80
debug = true

[frontend]
wasm_client_package = "gitlab.com/verygoodsoftwarenotvirus/todo/client/v1/frontend"

[auth]
cookie_secret = "HEREISA32CHARSECRETWHICHISMADEUP"

[database]
type = "postgres"
debug = false
connection_details = "postgres://dbuser:hunter2@database:5432/todo?sslmode=disable"
