[meta]
# tracing_enabled = true
# debug = true

[metrics]
metrics_provider = "prometheus"
tracing_provider = "jaeger"

[server]
http_port = 8888
debug = true

[frontend]
static_files_dir = "/frontend"

[auth]
cookie_secret = "HEREISA32CHARSECRETWHICHISMADEUP"

[database]
provider = "postgres"
debug = false
connection_details = "postgres://dbuser:hunter2@database:5432/todo?sslmode=disable"
