[meta]
# tracing_enabled = true
# debug = true

[metrics]
metrics_namespace = "todo_server"
metrics_provider = "prometheus"
tracing_provider = "jaeger"

[server]
http_port = 80
debug = true
frontend_files_directory = "/frontend"

[auth]
cookie_secret = "HEREISA32CHARSECRETWHICHISMADEUP"

[database]
type = "postgres"
debug = false
connection_details = "postgres://dbuser:hunter2@database:5432/todo?sslmode=disable"

# [database]
# type = "sqlite"
# debug = false
# connection_details = ":memory:"
