[meta]
    debug = false
    startup_deadline = "1m"

[server]
    debug = false
    http_port = 8888

[frontend]
    debug = false
    static_files_dir = "/frontend"
	cache_static_files = true

[auth]
    debug = false
	cookie_domain = ""
    cookie_secret = "HEREISA32CHARSECRETWHICHISMADEUP"
	cookie_lifetime = "24h"
	secure_cookies_only = false
	enable_user_signup = true

[metrics]
    metrics_provider = "prometheus"
    tracing_provider = "jaeger"
    database_metrics_collection_interval = "1s"
    runtime_metrics_collection_interval = "1s"

[database]
    debug = false
    provider = "postgres"
    connection_details = "postgres://dbuser:hunter2@database:5432/todo?sslmode=disable"
