enum permission {
  CAN_CYCLE_COOKIE_SECRET = 0x1,
  RESERVED_UNUSED_PERMISSION_2,
  RESERVED_UNUSED_PERMISSION_3,
  RESERVED_UNUSED_PERMISSION_4,
  RESERVED_UNUSED_PERMISSION_5,
  RESERVED_UNUSED_PERMISSION_6,
  RESERVED_UNUSED_PERMISSION_7,
  RESERVED_UNUSED_PERMISSION_8,
  RESERVED_UNUSED_PERMISSION_9,
  RESERVED_UNUSED_PERMISSION_10,
  RESERVED_UNUSED_PERMISSION_11,
  RESERVED_UNUSED_PERMISSION_12,
  RESERVED_UNUSED_PERMISSION_13,
  RESERVED_UNUSED_PERMISSION_14,
  RESERVED_UNUSED_PERMISSION_15,
  RESERVED_UNUSED_PERMISSION_16,
  RESERVED_UNUSED_PERMISSION_17,
  RESERVED_UNUSED_PERMISSION_18,
  RESERVED_UNUSED_PERMISSION_19,
  RESERVED_UNUSED_PERMISSION_20,
  RESERVED_UNUSED_PERMISSION_21,
  RESERVED_UNUSED_PERMISSION_22,
  RESERVED_UNUSED_PERMISSION_23,
  RESERVED_UNUSED_PERMISSION_24,
  RESERVED_UNUSED_PERMISSION_25,
  RESERVED_UNUSED_PERMISSION_26,
  RESERVED_UNUSED_PERMISSION_27,
  RESERVED_UNUSED_PERMISSION_28,
  RESERVED_UNUSED_PERMISSION_29,
  RESERVED_UNUSED_PERMISSION_30,
  RESERVED_UNUSED_PERMISSION_31,
  RESERVED_UNUSED_PERMISSION_32,
}

export class AdminPermissions {
  perms: number;

  constructor(perms: number) {
    this.perms = Math.max(0, perms);
  }

  canCycleCookieSecret(): boolean {
    return (this.perms & permission.CAN_CYCLE_COOKIE_SECRET) !== 0;
  }
}
