// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/item.proto

package todoproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateItemRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Details              string   `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateItemRequest) Reset()         { *m = CreateItemRequest{} }
func (m *CreateItemRequest) String() string { return proto.CompactTextString(m) }
func (*CreateItemRequest) ProtoMessage()    {}
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08ac4abb92d7f73c, []int{0}
}

func (m *CreateItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateItemRequest.Unmarshal(m, b)
}
func (m *CreateItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateItemRequest.Marshal(b, m, deterministic)
}
func (m *CreateItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateItemRequest.Merge(m, src)
}
func (m *CreateItemRequest) XXX_Size() int {
	return xxx_messageInfo_CreateItemRequest.Size(m)
}
func (m *CreateItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateItemRequest proto.InternalMessageInfo

func (m *CreateItemRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateItemRequest) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

type CreateItemResponse struct {
	Item                 *Item    `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateItemResponse) Reset()         { *m = CreateItemResponse{} }
func (m *CreateItemResponse) String() string { return proto.CompactTextString(m) }
func (*CreateItemResponse) ProtoMessage()    {}
func (*CreateItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08ac4abb92d7f73c, []int{1}
}

func (m *CreateItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateItemResponse.Unmarshal(m, b)
}
func (m *CreateItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateItemResponse.Marshal(b, m, deterministic)
}
func (m *CreateItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateItemResponse.Merge(m, src)
}
func (m *CreateItemResponse) XXX_Size() int {
	return xxx_messageInfo_CreateItemResponse.Size(m)
}
func (m *CreateItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateItemResponse proto.InternalMessageInfo

func (m *CreateItemResponse) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type UpdateItemRequest struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateItemRequest) Reset()         { *m = UpdateItemRequest{} }
func (m *UpdateItemRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateItemRequest) ProtoMessage()    {}
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08ac4abb92d7f73c, []int{2}
}

func (m *UpdateItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateItemRequest.Unmarshal(m, b)
}
func (m *UpdateItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateItemRequest.Marshal(b, m, deterministic)
}
func (m *UpdateItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateItemRequest.Merge(m, src)
}
func (m *UpdateItemRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateItemRequest.Size(m)
}
func (m *UpdateItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateItemRequest proto.InternalMessageInfo

func (m *UpdateItemRequest) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type UpdateItemResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateItemResponse) Reset()         { *m = UpdateItemResponse{} }
func (m *UpdateItemResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateItemResponse) ProtoMessage()    {}
func (*UpdateItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08ac4abb92d7f73c, []int{3}
}

func (m *UpdateItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateItemResponse.Unmarshal(m, b)
}
func (m *UpdateItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateItemResponse.Marshal(b, m, deterministic)
}
func (m *UpdateItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateItemResponse.Merge(m, src)
}
func (m *UpdateItemResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateItemResponse.Size(m)
}
func (m *UpdateItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateItemResponse proto.InternalMessageInfo

type GetItemRequest struct {
	ItemId               uint64   `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	UserId               uint64   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetItemRequest) Reset()         { *m = GetItemRequest{} }
func (m *GetItemRequest) String() string { return proto.CompactTextString(m) }
func (*GetItemRequest) ProtoMessage()    {}
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08ac4abb92d7f73c, []int{4}
}

func (m *GetItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetItemRequest.Unmarshal(m, b)
}
func (m *GetItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetItemRequest.Marshal(b, m, deterministic)
}
func (m *GetItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetItemRequest.Merge(m, src)
}
func (m *GetItemRequest) XXX_Size() int {
	return xxx_messageInfo_GetItemRequest.Size(m)
}
func (m *GetItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetItemRequest proto.InternalMessageInfo

func (m *GetItemRequest) GetItemId() uint64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *GetItemRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetItemResponse struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetItemResponse) Reset()         { *m = GetItemResponse{} }
func (m *GetItemResponse) String() string { return proto.CompactTextString(m) }
func (*GetItemResponse) ProtoMessage()    {}
func (*GetItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08ac4abb92d7f73c, []int{5}
}

func (m *GetItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetItemResponse.Unmarshal(m, b)
}
func (m *GetItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetItemResponse.Marshal(b, m, deterministic)
}
func (m *GetItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetItemResponse.Merge(m, src)
}
func (m *GetItemResponse) XXX_Size() int {
	return xxx_messageInfo_GetItemResponse.Size(m)
}
func (m *GetItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetItemResponse proto.InternalMessageInfo

func (m *GetItemResponse) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type DeleteItemRequest struct {
	ItemId               uint64   `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	UserId               uint64   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteItemRequest) Reset()         { *m = DeleteItemRequest{} }
func (m *DeleteItemRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteItemRequest) ProtoMessage()    {}
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08ac4abb92d7f73c, []int{6}
}

func (m *DeleteItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteItemRequest.Unmarshal(m, b)
}
func (m *DeleteItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteItemRequest.Marshal(b, m, deterministic)
}
func (m *DeleteItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteItemRequest.Merge(m, src)
}
func (m *DeleteItemRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteItemRequest.Size(m)
}
func (m *DeleteItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteItemRequest proto.InternalMessageInfo

func (m *DeleteItemRequest) GetItemId() uint64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *DeleteItemRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ItemListRequest struct {
	Filter               *QueryFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	UserId               uint64       `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ItemListRequest) Reset()         { *m = ItemListRequest{} }
func (m *ItemListRequest) String() string { return proto.CompactTextString(m) }
func (*ItemListRequest) ProtoMessage()    {}
func (*ItemListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08ac4abb92d7f73c, []int{7}
}

func (m *ItemListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemListRequest.Unmarshal(m, b)
}
func (m *ItemListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemListRequest.Marshal(b, m, deterministic)
}
func (m *ItemListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemListRequest.Merge(m, src)
}
func (m *ItemListRequest) XXX_Size() int {
	return xxx_messageInfo_ItemListRequest.Size(m)
}
func (m *ItemListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ItemListRequest proto.InternalMessageInfo

func (m *ItemListRequest) GetFilter() *QueryFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ItemListRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ItemListResponse struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemListResponse) Reset()         { *m = ItemListResponse{} }
func (m *ItemListResponse) String() string { return proto.CompactTextString(m) }
func (*ItemListResponse) ProtoMessage()    {}
func (*ItemListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08ac4abb92d7f73c, []int{8}
}

func (m *ItemListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemListResponse.Unmarshal(m, b)
}
func (m *ItemListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemListResponse.Marshal(b, m, deterministic)
}
func (m *ItemListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemListResponse.Merge(m, src)
}
func (m *ItemListResponse) XXX_Size() int {
	return xxx_messageInfo_ItemListResponse.Size(m)
}
func (m *ItemListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ItemListResponse proto.InternalMessageInfo

func (m *ItemListResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type ItemCountResponse struct {
	Count                uint64   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemCountResponse) Reset()         { *m = ItemCountResponse{} }
func (m *ItemCountResponse) String() string { return proto.CompactTextString(m) }
func (*ItemCountResponse) ProtoMessage()    {}
func (*ItemCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08ac4abb92d7f73c, []int{9}
}

func (m *ItemCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemCountResponse.Unmarshal(m, b)
}
func (m *ItemCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemCountResponse.Marshal(b, m, deterministic)
}
func (m *ItemCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemCountResponse.Merge(m, src)
}
func (m *ItemCountResponse) XXX_Size() int {
	return xxx_messageInfo_ItemCountResponse.Size(m)
}
func (m *ItemCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ItemCountResponse proto.InternalMessageInfo

func (m *ItemCountResponse) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Item struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Details              string   `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	CreatedOn            uint64   `protobuf:"varint,4,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	UpdatedOn            uint64   `protobuf:"varint,5,opt,name=updated_on,json=updatedOn,proto3" json:"updated_on,omitempty"`
	CompletedOn          uint64   `protobuf:"varint,6,opt,name=completed_on,json=completedOn,proto3" json:"completed_on,omitempty"`
	BelongsTo            uint64   `protobuf:"varint,7,opt,name=belongs_to,json=belongsTo,proto3" json:"belongs_to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_08ac4abb92d7f73c, []int{10}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *Item) GetCreatedOn() uint64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *Item) GetUpdatedOn() uint64 {
	if m != nil {
		return m.UpdatedOn
	}
	return 0
}

func (m *Item) GetCompletedOn() uint64 {
	if m != nil {
		return m.CompletedOn
	}
	return 0
}

func (m *Item) GetBelongsTo() uint64 {
	if m != nil {
		return m.BelongsTo
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateItemRequest)(nil), "todoproto.CreateItemRequest")
	proto.RegisterType((*CreateItemResponse)(nil), "todoproto.CreateItemResponse")
	proto.RegisterType((*UpdateItemRequest)(nil), "todoproto.UpdateItemRequest")
	proto.RegisterType((*UpdateItemResponse)(nil), "todoproto.UpdateItemResponse")
	proto.RegisterType((*GetItemRequest)(nil), "todoproto.GetItemRequest")
	proto.RegisterType((*GetItemResponse)(nil), "todoproto.GetItemResponse")
	proto.RegisterType((*DeleteItemRequest)(nil), "todoproto.DeleteItemRequest")
	proto.RegisterType((*ItemListRequest)(nil), "todoproto.ItemListRequest")
	proto.RegisterType((*ItemListResponse)(nil), "todoproto.ItemListResponse")
	proto.RegisterType((*ItemCountResponse)(nil), "todoproto.ItemCountResponse")
	proto.RegisterType((*Item)(nil), "todoproto.Item")
}

func init() { proto.RegisterFile("v1/item.proto", fileDescriptor_08ac4abb92d7f73c) }

var fileDescriptor_08ac4abb92d7f73c = []byte{
	// 500 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0xc7, 0x9b, 0x34, 0x6d, 0xe9, 0x6d, 0xac, 0xf4, 0x34, 0x41, 0x08, 0x4c, 0x1a, 0x41, 0x48,
	0xf0, 0x52, 0xc4, 0x90, 0x10, 0x7b, 0x64, 0xa3, 0x43, 0x05, 0xa4, 0x89, 0x6a, 0xbc, 0xf0, 0x52,
	0x75, 0xb5, 0x41, 0x91, 0x9a, 0xb8, 0xc4, 0x0e, 0x12, 0x9f, 0x8e, 0x17, 0x3e, 0x18, 0xf2, 0xd9,
	0x4d, 0x9c, 0x36, 0xad, 0xc4, 0x5b, 0xee, 0xfe, 0xe7, 0x9f, 0xef, 0xce, 0x77, 0x81, 0xbb, 0xbf,
	0x5e, 0xbd, 0x4c, 0x14, 0x4f, 0x47, 0xab, 0x5c, 0x28, 0x81, 0x7d, 0x25, 0x98, 0xa0, 0xcf, 0x48,
	0x2b, 0xe9, 0x3c, 0xc9, 0x8c, 0x12, 0xbf, 0x83, 0xe1, 0x65, 0xce, 0xe7, 0x8a, 0x4f, 0x14, 0x4f,
	0xa7, 0xfc, 0x67, 0xc1, 0xa5, 0x42, 0x84, 0x20, 0x9b, 0xa7, 0x3c, 0xf4, 0x4e, 0xbd, 0xe7, 0xfd,
	0x29, 0x7d, 0x63, 0x08, 0x3d, 0xc6, 0xd5, 0x3c, 0x59, 0xca, 0xd0, 0x27, 0xf7, 0xda, 0x8c, 0xcf,
	0x01, 0x5d, 0x84, 0x5c, 0x89, 0x4c, 0x72, 0x7c, 0x0a, 0x81, 0x4e, 0x80, 0x82, 0x0f, 0xce, 0x06,
	0xa3, 0x32, 0x83, 0x11, 0x85, 0x91, 0x18, 0xbf, 0x85, 0xe1, 0xd7, 0x15, 0xdb, 0xb8, 0x7d, 0x7d,
	0xd2, 0xdb, 0x77, 0xf2, 0x18, 0xd0, 0x3d, 0x69, 0x2e, 0x8d, 0x2f, 0xe0, 0xe8, 0x03, 0x57, 0x2e,
	0xec, 0x01, 0xf4, 0x74, 0xfc, 0x2c, 0x61, 0xc4, 0x0b, 0xa6, 0x5d, 0x6d, 0x4e, 0x98, 0x16, 0x0a,
	0xc9, 0x73, 0x2d, 0xf8, 0x46, 0xd0, 0xe6, 0x84, 0xc5, 0x6f, 0x60, 0x50, 0x32, 0x36, 0x6a, 0xd9,
	0x9b, 0xd1, 0x18, 0x86, 0xef, 0xf9, 0x92, 0xd7, 0x6b, 0xf9, 0xff, 0xeb, 0xbf, 0xc1, 0x40, 0x03,
	0x3e, 0x27, 0x52, 0xad, 0x21, 0x23, 0xe8, 0x7e, 0x4f, 0x96, 0x8a, 0xe7, 0x36, 0x81, 0xfb, 0x4e,
	0x02, 0x5f, 0x0a, 0x9e, 0xff, 0xbe, 0x22, 0x75, 0x6a, 0xa3, 0x76, 0xb3, 0xcf, 0xe1, 0x5e, 0xc5,
	0xb6, 0xb5, 0x3d, 0x83, 0x8e, 0x4e, 0x49, 0x86, 0xde, 0x69, 0xbb, 0xa9, 0x38, 0xa3, 0xc6, 0x2f,
	0x60, 0xa8, 0xcd, 0x4b, 0x51, 0x64, 0xd5, 0xd9, 0x63, 0xe8, 0x2c, 0xb4, 0xc3, 0xd6, 0x66, 0x8c,
	0xf8, 0xaf, 0x07, 0x81, 0x8e, 0xc5, 0x23, 0xf0, 0xcb, 0xba, 0xfd, 0x84, 0x95, 0x63, 0xe5, 0x37,
	0x8f, 0x55, 0xbb, 0x36, 0x56, 0x78, 0x02, 0xb0, 0xa0, 0xb1, 0x62, 0x33, 0x91, 0x85, 0x01, 0x51,
	0xfa, 0xd6, 0x73, 0x9d, 0x69, 0xb9, 0xa0, 0x01, 0x20, 0xb9, 0x63, 0x64, 0xeb, 0xb9, 0xce, 0xf0,
	0x09, 0x1c, 0x2e, 0x44, 0xba, 0xd2, 0xef, 0x41, 0x01, 0x5d, 0x0a, 0x38, 0x28, 0x7d, 0x86, 0x70,
	0xcb, 0x97, 0x22, 0xfb, 0x21, 0x67, 0x4a, 0x84, 0x3d, 0x43, 0xb0, 0x9e, 0x1b, 0x71, 0xf6, 0xa7,
	0x0d, 0xc1, 0x8d, 0x60, 0x02, 0x2f, 0xa0, 0x67, 0x07, 0x02, 0x1f, 0x3a, 0xdd, 0xa9, 0x0f, 0x5a,
	0x14, 0x35, 0x49, 0x76, 0x2c, 0x5b, 0xf8, 0x11, 0x0e, 0xad, 0x93, 0x3a, 0x88, 0xd1, 0x46, 0x9b,
	0x9d, 0xe7, 0x8e, 0x1e, 0x6f, 0x68, 0xb5, 0x9e, 0xc7, 0x2d, 0x1c, 0xc3, 0x1d, 0xcb, 0x92, 0x7b,
	0x39, 0x8f, 0x1a, 0xb5, 0x12, 0xf3, 0x09, 0xa0, 0x5a, 0x5b, 0x74, 0x2f, 0xdd, 0xfa, 0x21, 0x44,
	0x27, 0x3b, 0x54, 0x17, 0x56, 0xad, 0x63, 0x0d, 0xb6, 0xb5, 0xdf, 0x35, 0x58, 0xc3, 0x0e, 0xb7,
	0xf0, 0x0a, 0xa0, 0xda, 0xa4, 0x1a, 0x6c, 0x6b, 0xc1, 0xa2, 0xd0, 0x51, 0xc7, 0x79, 0x2e, 0xf2,
	0x8a, 0x73, 0xdb, 0x25, 0xf7, 0xeb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xed, 0x61, 0xeb, 0x6f,
	0x0d, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodoClient is the client API for Todo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoClient interface {
	GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*GetItemResponse, error)
	GetItemCount(ctx context.Context, in *ItemListRequest, opts ...grpc.CallOption) (*ItemCountResponse, error)
	GetItems(ctx context.Context, in *ItemListRequest, opts ...grpc.CallOption) (*ItemListResponse, error)
	CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*CreateItemResponse, error)
	UpdateItem(ctx context.Context, in *UpdateItemRequest, opts ...grpc.CallOption) (*UpdateItemResponse, error)
	DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
}

type todoClient struct {
	cc *grpc.ClientConn
}

func NewTodoClient(cc *grpc.ClientConn) TodoClient {
	return &todoClient{cc}
}

func (c *todoClient) GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*GetItemResponse, error) {
	out := new(GetItemResponse)
	err := c.cc.Invoke(ctx, "/todoproto.Todo/GetItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) GetItemCount(ctx context.Context, in *ItemListRequest, opts ...grpc.CallOption) (*ItemCountResponse, error) {
	out := new(ItemCountResponse)
	err := c.cc.Invoke(ctx, "/todoproto.Todo/GetItemCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) GetItems(ctx context.Context, in *ItemListRequest, opts ...grpc.CallOption) (*ItemListResponse, error) {
	out := new(ItemListResponse)
	err := c.cc.Invoke(ctx, "/todoproto.Todo/GetItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*CreateItemResponse, error) {
	out := new(CreateItemResponse)
	err := c.cc.Invoke(ctx, "/todoproto.Todo/CreateItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) UpdateItem(ctx context.Context, in *UpdateItemRequest, opts ...grpc.CallOption) (*UpdateItemResponse, error) {
	out := new(UpdateItemResponse)
	err := c.cc.Invoke(ctx, "/todoproto.Todo/UpdateItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, "/todoproto.Todo/DeleteItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServer is the server API for Todo service.
type TodoServer interface {
	GetItem(context.Context, *GetItemRequest) (*GetItemResponse, error)
	GetItemCount(context.Context, *ItemListRequest) (*ItemCountResponse, error)
	GetItems(context.Context, *ItemListRequest) (*ItemListResponse, error)
	CreateItem(context.Context, *CreateItemRequest) (*CreateItemResponse, error)
	UpdateItem(context.Context, *UpdateItemRequest) (*UpdateItemResponse, error)
	DeleteItem(context.Context, *DeleteItemRequest) (*ErrorResponse, error)
}

func RegisterTodoServer(s *grpc.Server, srv TodoServer) {
	s.RegisterService(&_Todo_serviceDesc, srv)
}

func _Todo_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todoproto.Todo/GetItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).GetItem(ctx, req.(*GetItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_GetItemCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).GetItemCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todoproto.Todo/GetItemCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).GetItemCount(ctx, req.(*ItemListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_GetItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).GetItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todoproto.Todo/GetItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).GetItems(ctx, req.(*ItemListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_CreateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).CreateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todoproto.Todo/CreateItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).CreateItem(ctx, req.(*CreateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_UpdateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).UpdateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todoproto.Todo/UpdateItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).UpdateItem(ctx, req.(*UpdateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_DeleteItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).DeleteItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todoproto.Todo/DeleteItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).DeleteItem(ctx, req.(*DeleteItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Todo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todoproto.Todo",
	HandlerType: (*TodoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetItem",
			Handler:    _Todo_GetItem_Handler,
		},
		{
			MethodName: "GetItemCount",
			Handler:    _Todo_GetItemCount_Handler,
		},
		{
			MethodName: "GetItems",
			Handler:    _Todo_GetItems_Handler,
		},
		{
			MethodName: "CreateItem",
			Handler:    _Todo_CreateItem_Handler,
		},
		{
			MethodName: "UpdateItem",
			Handler:    _Todo_UpdateItem_Handler,
		},
		{
			MethodName: "DeleteItem",
			Handler:    _Todo_DeleteItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/item.proto",
}
