// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/main.proto

package todoproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code                 uint32   `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea852adc64ca91b7, []int{0}
}

func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (m *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(m, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ErrorResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type QueryFilter struct {
	Page                 uint64   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                uint64   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	CreatedAfter         uint64   `protobuf:"varint,3,opt,name=created_after,json=createdAfter,proto3" json:"created_after,omitempty"`
	CreatedBefore        uint64   `protobuf:"varint,4,opt,name=created_before,json=createdBefore,proto3" json:"created_before,omitempty"`
	UpdatedAfter         uint64   `protobuf:"varint,5,opt,name=updated_after,json=updatedAfter,proto3" json:"updated_after,omitempty"`
	UpdatedBefore        uint64   `protobuf:"varint,6,opt,name=updated_before,json=updatedBefore,proto3" json:"updated_before,omitempty"`
	IncludeAll           bool     `protobuf:"varint,7,opt,name=include_all,json=includeAll,proto3" json:"include_all,omitempty"`
	SortBy               string   `protobuf:"bytes,8,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryFilter) Reset()         { *m = QueryFilter{} }
func (m *QueryFilter) String() string { return proto.CompactTextString(m) }
func (*QueryFilter) ProtoMessage()    {}
func (*QueryFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea852adc64ca91b7, []int{1}
}

func (m *QueryFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryFilter.Unmarshal(m, b)
}
func (m *QueryFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryFilter.Marshal(b, m, deterministic)
}
func (m *QueryFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFilter.Merge(m, src)
}
func (m *QueryFilter) XXX_Size() int {
	return xxx_messageInfo_QueryFilter.Size(m)
}
func (m *QueryFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFilter.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFilter proto.InternalMessageInfo

func (m *QueryFilter) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *QueryFilter) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *QueryFilter) GetCreatedAfter() uint64 {
	if m != nil {
		return m.CreatedAfter
	}
	return 0
}

func (m *QueryFilter) GetCreatedBefore() uint64 {
	if m != nil {
		return m.CreatedBefore
	}
	return 0
}

func (m *QueryFilter) GetUpdatedAfter() uint64 {
	if m != nil {
		return m.UpdatedAfter
	}
	return 0
}

func (m *QueryFilter) GetUpdatedBefore() uint64 {
	if m != nil {
		return m.UpdatedBefore
	}
	return 0
}

func (m *QueryFilter) GetIncludeAll() bool {
	if m != nil {
		return m.IncludeAll
	}
	return false
}

func (m *QueryFilter) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

type Pagination struct {
	Page                 uint64   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                uint64   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	TotalCount           uint64   `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea852adc64ca91b7, []int{2}
}

func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Pagination) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Pagination) GetTotalCount() uint64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func init() {
	proto.RegisterType((*ErrorResponse)(nil), "todoproto.ErrorResponse")
	proto.RegisterType((*QueryFilter)(nil), "todoproto.QueryFilter")
	proto.RegisterType((*Pagination)(nil), "todoproto.Pagination")
}

func init() { proto.RegisterFile("v1/main.proto", fileDescriptor_ea852adc64ca91b7) }

var fileDescriptor_ea852adc64ca91b7 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0x86, 0xe9, 0xda, 0xfd, 0x9a, 0xb5, 0x1e, 0x82, 0x60, 0x6e, 0x5b, 0x2a, 0x42, 0x4f, 0x8a,
	0x78, 0xf6, 0xb0, 0x2b, 0x7a, 0xd6, 0x5c, 0x3c, 0x96, 0xb4, 0x9d, 0x5d, 0x02, 0x69, 0xa6, 0xa4,
	0xa9, 0xd0, 0x9f, 0xe0, 0xbf, 0x96, 0xa6, 0xa9, 0x78, 0xf5, 0x36, 0xf3, 0xe4, 0x9d, 0xe7, 0xf0,
	0x06, 0x92, 0xaf, 0xc7, 0x87, 0x46, 0x2a, 0x73, 0xdf, 0x5a, 0x72, 0xc4, 0xb6, 0x8e, 0x6a, 0xf2,
	0x63, 0xf6, 0x0c, 0xc9, 0xab, 0xb5, 0x64, 0x05, 0x76, 0x2d, 0x99, 0x0e, 0x19, 0x87, 0x75, 0x83,
	0x5d, 0x27, 0xcf, 0xc8, 0xa3, 0x34, 0xca, 0xb7, 0x62, 0x5e, 0x19, 0x83, 0xb8, 0xa2, 0x1a, 0xf9,
	0x22, 0x8d, 0xf2, 0x44, 0xf8, 0x39, 0xfb, 0x5e, 0xc0, 0xee, 0xa3, 0x47, 0x3b, 0xbc, 0x29, 0xed,
	0xd0, 0x8e, 0x99, 0x76, 0x3e, 0x8d, 0x85, 0x9f, 0xd9, 0x35, 0x2c, 0xb5, 0x6a, 0x94, 0xf3, 0x87,
	0xb1, 0x98, 0x16, 0x76, 0x0b, 0x49, 0x65, 0x51, 0x3a, 0xac, 0x0b, 0x79, 0x72, 0x68, 0xf9, 0x85,
	0x7f, 0xbd, 0x0c, 0xf0, 0x30, 0x32, 0x76, 0x07, 0x57, 0x73, 0xa8, 0xc4, 0x13, 0x59, 0xe4, 0xb1,
	0x4f, 0xcd, 0xa7, 0x47, 0x0f, 0x47, 0x57, 0xdf, 0xd6, 0x7f, 0x5c, 0xcb, 0xc9, 0x15, 0xe0, 0xaf,
	0x6b, 0x0e, 0x05, 0xd7, 0x6a, 0x72, 0x05, 0x1a, 0x5c, 0x7b, 0xd8, 0x29, 0x53, 0xe9, 0xbe, 0xc6,
	0x42, 0x6a, 0xcd, 0xd7, 0x69, 0x94, 0x6f, 0x04, 0x04, 0x74, 0xd0, 0x9a, 0xdd, 0xc0, 0xba, 0x23,
	0xeb, 0x8a, 0x72, 0xe0, 0x1b, 0x5f, 0xd0, 0x6a, 0x5c, 0x8f, 0x43, 0xf6, 0x09, 0xf0, 0x2e, 0xcf,
	0xca, 0x48, 0xa7, 0xc8, 0xfc, 0xa3, 0x89, 0x3d, 0xec, 0x1c, 0x39, 0xa9, 0x8b, 0x8a, 0x7a, 0xe3,
	0x42, 0x0f, 0xe0, 0xd1, 0xcb, 0x48, 0xca, 0x95, 0xff, 0xaa, 0xa7, 0x9f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xad, 0x3a, 0x37, 0x0d, 0xc6, 0x01, 0x00, 0x00,
}
