// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/main.proto

package todoproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code                 uint32   `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea852adc64ca91b7, []int{0}
}

func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (m *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(m, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ErrorResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*ErrorResponse)(nil), "todoproto.ErrorResponse")
}

func init() { proto.RegisterFile("v1/main.proto", fileDescriptor_ea852adc64ca91b7) }

var fileDescriptor_ea852adc64ca91b7 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xcd, 0x4e, 0x83, 0x40,
	0x10, 0x80, 0x8b, 0x36, 0xd6, 0x4e, 0xe4, 0x32, 0x27, 0x44, 0x4d, 0x1a, 0x4e, 0x3d, 0x61, 0xd4,
	0xb3, 0x17, 0x6b, 0x35, 0xfe, 0x9c, 0x88, 0x3e, 0x00, 0xca, 0xc4, 0x90, 0xb8, 0x0c, 0xee, 0x4e,
	0x7d, 0x3d, 0x5f, 0xcd, 0x74, 0x61, 0x61, 0x35, 0xab, 0xb7, 0xe1, 0xfb, 0xd8, 0x6f, 0xb2, 0x59,
	0x88, 0x3f, 0xcf, 0x4e, 0x55, 0x59, 0x37, 0x79, 0xab, 0x59, 0x18, 0xe7, 0xc2, 0x15, 0xdb, 0x31,
	0xdd, 0x9a, 0x5a, 0x48, 0x75, 0x26, 0xbb, 0x84, 0x78, 0xad, 0x35, 0xeb, 0x82, 0x4c, 0xcb, 0x8d,
	0x21, 0x4c, 0x60, 0xa6, 0xc8, 0x98, 0xf2, 0x8d, 0x92, 0x68, 0x11, 0x2d, 0xe7, 0x85, 0xfb, 0x44,
	0x84, 0xe9, 0x2b, 0x57, 0x94, 0xec, 0x2c, 0xa2, 0x65, 0x5c, 0xd8, 0xf9, 0xfc, 0x6b, 0x17, 0xa6,
	0x4f, 0x5c, 0x31, 0x5e, 0xc1, 0xec, 0x96, 0xe4, 0x4e, 0x48, 0xe1, 0x61, 0x3e, 0x6c, 0xcb, 0x7b,
	0x56, 0xd0, 0xc7, 0x86, 0x8c, 0xa4, 0x69, 0x48, 0x75, 0x8b, 0xb3, 0x09, 0xde, 0xc3, 0x41, 0x0f,
	0x57, 0xbc, 0x69, 0x04, 0xfd, 0xbf, 0xb7, 0xf4, 0xb1, 0x36, 0xe2, 0x4a, 0xc7, 0xbf, 0x9c, 0x3d,
	0xe1, 0xb5, 0xd6, 0xb0, 0xdf, 0xb7, 0xcc, 0xbf, 0x9d, 0xa3, 0xa0, 0x1b, 0x32, 0x0f, 0x00, 0x2b,
	0x4d, 0xa5, 0x90, 0xbd, 0x99, 0xbf, 0x74, 0xc4, 0x2e, 0x75, 0xf2, 0x87, 0xf5, 0x63, 0xcf, 0x6d,
	0x15, 0x8a, 0x8d, 0x38, 0x14, 0xf3, 0xed, 0x10, 0xbb, 0x01, 0xb8, 0xa6, 0x77, 0x0a, 0xc4, 0x46,
	0xec, 0x62, 0x89, 0x67, 0x7f, 0xbc, 0x76, 0x36, 0x79, 0xd9, 0xb3, 0xf8, 0xe2, 0x3b, 0x00, 0x00,
	0xff, 0xff, 0x23, 0xab, 0x50, 0x5b, 0x32, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodoClient is the client API for Todo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoClient interface {
	// Items
	GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*GetItemResponse, error)
	GetItemCount(ctx context.Context, in *ItemListRequest, opts ...grpc.CallOption) (*ItemCountResponse, error)
	GetItems(ctx context.Context, in *ItemListRequest, opts ...grpc.CallOption) (*ItemListResponse, error)
	CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*CreateItemResponse, error)
	UpdateItem(ctx context.Context, in *UpdateItemRequest, opts ...grpc.CallOption) (*UpdateItemResponse, error)
	DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
}

type todoClient struct {
	cc *grpc.ClientConn
}

func NewTodoClient(cc *grpc.ClientConn) TodoClient {
	return &todoClient{cc}
}

func (c *todoClient) GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*GetItemResponse, error) {
	out := new(GetItemResponse)
	err := c.cc.Invoke(ctx, "/todoproto.Todo/GetItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) GetItemCount(ctx context.Context, in *ItemListRequest, opts ...grpc.CallOption) (*ItemCountResponse, error) {
	out := new(ItemCountResponse)
	err := c.cc.Invoke(ctx, "/todoproto.Todo/GetItemCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) GetItems(ctx context.Context, in *ItemListRequest, opts ...grpc.CallOption) (*ItemListResponse, error) {
	out := new(ItemListResponse)
	err := c.cc.Invoke(ctx, "/todoproto.Todo/GetItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*CreateItemResponse, error) {
	out := new(CreateItemResponse)
	err := c.cc.Invoke(ctx, "/todoproto.Todo/CreateItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) UpdateItem(ctx context.Context, in *UpdateItemRequest, opts ...grpc.CallOption) (*UpdateItemResponse, error) {
	out := new(UpdateItemResponse)
	err := c.cc.Invoke(ctx, "/todoproto.Todo/UpdateItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, "/todoproto.Todo/DeleteItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServer is the server API for Todo service.
type TodoServer interface {
	// Items
	GetItem(context.Context, *GetItemRequest) (*GetItemResponse, error)
	GetItemCount(context.Context, *ItemListRequest) (*ItemCountResponse, error)
	GetItems(context.Context, *ItemListRequest) (*ItemListResponse, error)
	CreateItem(context.Context, *CreateItemRequest) (*CreateItemResponse, error)
	UpdateItem(context.Context, *UpdateItemRequest) (*UpdateItemResponse, error)
	DeleteItem(context.Context, *DeleteItemRequest) (*ErrorResponse, error)
}

func RegisterTodoServer(s *grpc.Server, srv TodoServer) {
	s.RegisterService(&_Todo_serviceDesc, srv)
}

func _Todo_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todoproto.Todo/GetItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).GetItem(ctx, req.(*GetItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_GetItemCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).GetItemCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todoproto.Todo/GetItemCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).GetItemCount(ctx, req.(*ItemListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_GetItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).GetItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todoproto.Todo/GetItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).GetItems(ctx, req.(*ItemListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_CreateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).CreateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todoproto.Todo/CreateItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).CreateItem(ctx, req.(*CreateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_UpdateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).UpdateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todoproto.Todo/UpdateItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).UpdateItem(ctx, req.(*UpdateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_DeleteItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).DeleteItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todoproto.Todo/DeleteItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).DeleteItem(ctx, req.(*DeleteItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Todo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todoproto.Todo",
	HandlerType: (*TodoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetItem",
			Handler:    _Todo_GetItem_Handler,
		},
		{
			MethodName: "GetItemCount",
			Handler:    _Todo_GetItemCount_Handler,
		},
		{
			MethodName: "GetItems",
			Handler:    _Todo_GetItems_Handler,
		},
		{
			MethodName: "CreateItem",
			Handler:    _Todo_CreateItem_Handler,
		},
		{
			MethodName: "UpdateItem",
			Handler:    _Todo_UpdateItem_Handler,
		},
		{
			MethodName: "DeleteItem",
			Handler:    _Todo_DeleteItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/main.proto",
}
