// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/oauth2_client.proto

package todoproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateOAuth2ClientRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Details              string   `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOAuth2ClientRequest) Reset()         { *m = CreateOAuth2ClientRequest{} }
func (m *CreateOAuth2ClientRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOAuth2ClientRequest) ProtoMessage()    {}
func (*CreateOAuth2ClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6bb9b72a357a6c, []int{0}
}

func (m *CreateOAuth2ClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOAuth2ClientRequest.Unmarshal(m, b)
}
func (m *CreateOAuth2ClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOAuth2ClientRequest.Marshal(b, m, deterministic)
}
func (m *CreateOAuth2ClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOAuth2ClientRequest.Merge(m, src)
}
func (m *CreateOAuth2ClientRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOAuth2ClientRequest.Size(m)
}
func (m *CreateOAuth2ClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOAuth2ClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOAuth2ClientRequest proto.InternalMessageInfo

func (m *CreateOAuth2ClientRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateOAuth2ClientRequest) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

type CreateOAuth2ClientResponse struct {
	Client               *OAuth2Client `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateOAuth2ClientResponse) Reset()         { *m = CreateOAuth2ClientResponse{} }
func (m *CreateOAuth2ClientResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOAuth2ClientResponse) ProtoMessage()    {}
func (*CreateOAuth2ClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6bb9b72a357a6c, []int{1}
}

func (m *CreateOAuth2ClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOAuth2ClientResponse.Unmarshal(m, b)
}
func (m *CreateOAuth2ClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOAuth2ClientResponse.Marshal(b, m, deterministic)
}
func (m *CreateOAuth2ClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOAuth2ClientResponse.Merge(m, src)
}
func (m *CreateOAuth2ClientResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOAuth2ClientResponse.Size(m)
}
func (m *CreateOAuth2ClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOAuth2ClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOAuth2ClientResponse proto.InternalMessageInfo

func (m *CreateOAuth2ClientResponse) GetClient() *OAuth2Client {
	if m != nil {
		return m.Client
	}
	return nil
}

type UpdateOAuth2ClientRequest struct {
	Client               *OAuth2Client `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateOAuth2ClientRequest) Reset()         { *m = UpdateOAuth2ClientRequest{} }
func (m *UpdateOAuth2ClientRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateOAuth2ClientRequest) ProtoMessage()    {}
func (*UpdateOAuth2ClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6bb9b72a357a6c, []int{2}
}

func (m *UpdateOAuth2ClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOAuth2ClientRequest.Unmarshal(m, b)
}
func (m *UpdateOAuth2ClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOAuth2ClientRequest.Marshal(b, m, deterministic)
}
func (m *UpdateOAuth2ClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOAuth2ClientRequest.Merge(m, src)
}
func (m *UpdateOAuth2ClientRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateOAuth2ClientRequest.Size(m)
}
func (m *UpdateOAuth2ClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOAuth2ClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOAuth2ClientRequest proto.InternalMessageInfo

func (m *UpdateOAuth2ClientRequest) GetClient() *OAuth2Client {
	if m != nil {
		return m.Client
	}
	return nil
}

type UpdateOAuth2ClientResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateOAuth2ClientResponse) Reset()         { *m = UpdateOAuth2ClientResponse{} }
func (m *UpdateOAuth2ClientResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateOAuth2ClientResponse) ProtoMessage()    {}
func (*UpdateOAuth2ClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6bb9b72a357a6c, []int{3}
}

func (m *UpdateOAuth2ClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOAuth2ClientResponse.Unmarshal(m, b)
}
func (m *UpdateOAuth2ClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOAuth2ClientResponse.Marshal(b, m, deterministic)
}
func (m *UpdateOAuth2ClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOAuth2ClientResponse.Merge(m, src)
}
func (m *UpdateOAuth2ClientResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateOAuth2ClientResponse.Size(m)
}
func (m *UpdateOAuth2ClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOAuth2ClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOAuth2ClientResponse proto.InternalMessageInfo

type GetOAuth2ClientRequest struct {
	ClientId             uint64   `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserId               uint64   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOAuth2ClientRequest) Reset()         { *m = GetOAuth2ClientRequest{} }
func (m *GetOAuth2ClientRequest) String() string { return proto.CompactTextString(m) }
func (*GetOAuth2ClientRequest) ProtoMessage()    {}
func (*GetOAuth2ClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6bb9b72a357a6c, []int{4}
}

func (m *GetOAuth2ClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOAuth2ClientRequest.Unmarshal(m, b)
}
func (m *GetOAuth2ClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOAuth2ClientRequest.Marshal(b, m, deterministic)
}
func (m *GetOAuth2ClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOAuth2ClientRequest.Merge(m, src)
}
func (m *GetOAuth2ClientRequest) XXX_Size() int {
	return xxx_messageInfo_GetOAuth2ClientRequest.Size(m)
}
func (m *GetOAuth2ClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOAuth2ClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOAuth2ClientRequest proto.InternalMessageInfo

func (m *GetOAuth2ClientRequest) GetClientId() uint64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *GetOAuth2ClientRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetOAuth2ClientResponse struct {
	Client               *OAuth2Client `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetOAuth2ClientResponse) Reset()         { *m = GetOAuth2ClientResponse{} }
func (m *GetOAuth2ClientResponse) String() string { return proto.CompactTextString(m) }
func (*GetOAuth2ClientResponse) ProtoMessage()    {}
func (*GetOAuth2ClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6bb9b72a357a6c, []int{5}
}

func (m *GetOAuth2ClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOAuth2ClientResponse.Unmarshal(m, b)
}
func (m *GetOAuth2ClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOAuth2ClientResponse.Marshal(b, m, deterministic)
}
func (m *GetOAuth2ClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOAuth2ClientResponse.Merge(m, src)
}
func (m *GetOAuth2ClientResponse) XXX_Size() int {
	return xxx_messageInfo_GetOAuth2ClientResponse.Size(m)
}
func (m *GetOAuth2ClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOAuth2ClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOAuth2ClientResponse proto.InternalMessageInfo

func (m *GetOAuth2ClientResponse) GetClient() *OAuth2Client {
	if m != nil {
		return m.Client
	}
	return nil
}

type DeleteOAuth2ClientRequest struct {
	ClientId             uint64   `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserId               uint64   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOAuth2ClientRequest) Reset()         { *m = DeleteOAuth2ClientRequest{} }
func (m *DeleteOAuth2ClientRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteOAuth2ClientRequest) ProtoMessage()    {}
func (*DeleteOAuth2ClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6bb9b72a357a6c, []int{6}
}

func (m *DeleteOAuth2ClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOAuth2ClientRequest.Unmarshal(m, b)
}
func (m *DeleteOAuth2ClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOAuth2ClientRequest.Marshal(b, m, deterministic)
}
func (m *DeleteOAuth2ClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOAuth2ClientRequest.Merge(m, src)
}
func (m *DeleteOAuth2ClientRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteOAuth2ClientRequest.Size(m)
}
func (m *DeleteOAuth2ClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOAuth2ClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOAuth2ClientRequest proto.InternalMessageInfo

func (m *DeleteOAuth2ClientRequest) GetClientId() uint64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *DeleteOAuth2ClientRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type OAuth2ClientListRequest struct {
	Filter               *QueryFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	UserId               uint64       `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *OAuth2ClientListRequest) Reset()         { *m = OAuth2ClientListRequest{} }
func (m *OAuth2ClientListRequest) String() string { return proto.CompactTextString(m) }
func (*OAuth2ClientListRequest) ProtoMessage()    {}
func (*OAuth2ClientListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6bb9b72a357a6c, []int{7}
}

func (m *OAuth2ClientListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuth2ClientListRequest.Unmarshal(m, b)
}
func (m *OAuth2ClientListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuth2ClientListRequest.Marshal(b, m, deterministic)
}
func (m *OAuth2ClientListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuth2ClientListRequest.Merge(m, src)
}
func (m *OAuth2ClientListRequest) XXX_Size() int {
	return xxx_messageInfo_OAuth2ClientListRequest.Size(m)
}
func (m *OAuth2ClientListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuth2ClientListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OAuth2ClientListRequest proto.InternalMessageInfo

func (m *OAuth2ClientListRequest) GetFilter() *QueryFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *OAuth2ClientListRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type OAuth2ClientListResponse struct {
	Clients              []*OAuth2Client `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *OAuth2ClientListResponse) Reset()         { *m = OAuth2ClientListResponse{} }
func (m *OAuth2ClientListResponse) String() string { return proto.CompactTextString(m) }
func (*OAuth2ClientListResponse) ProtoMessage()    {}
func (*OAuth2ClientListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6bb9b72a357a6c, []int{8}
}

func (m *OAuth2ClientListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuth2ClientListResponse.Unmarshal(m, b)
}
func (m *OAuth2ClientListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuth2ClientListResponse.Marshal(b, m, deterministic)
}
func (m *OAuth2ClientListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuth2ClientListResponse.Merge(m, src)
}
func (m *OAuth2ClientListResponse) XXX_Size() int {
	return xxx_messageInfo_OAuth2ClientListResponse.Size(m)
}
func (m *OAuth2ClientListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuth2ClientListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OAuth2ClientListResponse proto.InternalMessageInfo

func (m *OAuth2ClientListResponse) GetClients() []*OAuth2Client {
	if m != nil {
		return m.Clients
	}
	return nil
}

type OAuth2ClientCountResponse struct {
	Count                uint64   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OAuth2ClientCountResponse) Reset()         { *m = OAuth2ClientCountResponse{} }
func (m *OAuth2ClientCountResponse) String() string { return proto.CompactTextString(m) }
func (*OAuth2ClientCountResponse) ProtoMessage()    {}
func (*OAuth2ClientCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6bb9b72a357a6c, []int{9}
}

func (m *OAuth2ClientCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuth2ClientCountResponse.Unmarshal(m, b)
}
func (m *OAuth2ClientCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuth2ClientCountResponse.Marshal(b, m, deterministic)
}
func (m *OAuth2ClientCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuth2ClientCountResponse.Merge(m, src)
}
func (m *OAuth2ClientCountResponse) XXX_Size() int {
	return xxx_messageInfo_OAuth2ClientCountResponse.Size(m)
}
func (m *OAuth2ClientCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuth2ClientCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OAuth2ClientCountResponse proto.InternalMessageInfo

func (m *OAuth2ClientCountResponse) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type OAuth2Client struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Details              string   `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	CreatedOn            uint64   `protobuf:"varint,4,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	UpdatedOn            uint64   `protobuf:"varint,5,opt,name=updated_on,json=updatedOn,proto3" json:"updated_on,omitempty"`
	CompletedOn          uint64   `protobuf:"varint,6,opt,name=completed_on,json=completedOn,proto3" json:"completed_on,omitempty"`
	BelongsTo            uint64   `protobuf:"varint,7,opt,name=belongs_to,json=belongsTo,proto3" json:"belongs_to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OAuth2Client) Reset()         { *m = OAuth2Client{} }
func (m *OAuth2Client) String() string { return proto.CompactTextString(m) }
func (*OAuth2Client) ProtoMessage()    {}
func (*OAuth2Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f6bb9b72a357a6c, []int{10}
}

func (m *OAuth2Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuth2Client.Unmarshal(m, b)
}
func (m *OAuth2Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuth2Client.Marshal(b, m, deterministic)
}
func (m *OAuth2Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuth2Client.Merge(m, src)
}
func (m *OAuth2Client) XXX_Size() int {
	return xxx_messageInfo_OAuth2Client.Size(m)
}
func (m *OAuth2Client) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuth2Client.DiscardUnknown(m)
}

var xxx_messageInfo_OAuth2Client proto.InternalMessageInfo

func (m *OAuth2Client) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OAuth2Client) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OAuth2Client) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *OAuth2Client) GetCreatedOn() uint64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *OAuth2Client) GetUpdatedOn() uint64 {
	if m != nil {
		return m.UpdatedOn
	}
	return 0
}

func (m *OAuth2Client) GetCompletedOn() uint64 {
	if m != nil {
		return m.CompletedOn
	}
	return 0
}

func (m *OAuth2Client) GetBelongsTo() uint64 {
	if m != nil {
		return m.BelongsTo
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateOAuth2ClientRequest)(nil), "todoproto.CreateOAuth2ClientRequest")
	proto.RegisterType((*CreateOAuth2ClientResponse)(nil), "todoproto.CreateOAuth2ClientResponse")
	proto.RegisterType((*UpdateOAuth2ClientRequest)(nil), "todoproto.UpdateOAuth2ClientRequest")
	proto.RegisterType((*UpdateOAuth2ClientResponse)(nil), "todoproto.UpdateOAuth2ClientResponse")
	proto.RegisterType((*GetOAuth2ClientRequest)(nil), "todoproto.GetOAuth2ClientRequest")
	proto.RegisterType((*GetOAuth2ClientResponse)(nil), "todoproto.GetOAuth2ClientResponse")
	proto.RegisterType((*DeleteOAuth2ClientRequest)(nil), "todoproto.DeleteOAuth2ClientRequest")
	proto.RegisterType((*OAuth2ClientListRequest)(nil), "todoproto.OAuth2ClientListRequest")
	proto.RegisterType((*OAuth2ClientListResponse)(nil), "todoproto.OAuth2ClientListResponse")
	proto.RegisterType((*OAuth2ClientCountResponse)(nil), "todoproto.OAuth2ClientCountResponse")
	proto.RegisterType((*OAuth2Client)(nil), "todoproto.OAuth2Client")
}

func init() { proto.RegisterFile("v1/oauth2_client.proto", fileDescriptor_7f6bb9b72a357a6c) }

var fileDescriptor_7f6bb9b72a357a6c = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xd1, 0x8e, 0x9a, 0x40,
	0x14, 0x0d, 0xa8, 0x50, 0xae, 0xa6, 0x0f, 0x93, 0x56, 0xc0, 0xb6, 0x89, 0xe5, 0xa9, 0x4f, 0x18,
	0xec, 0x17, 0x34, 0x36, 0x6d, 0x6c, 0xb4, 0x46, 0xd2, 0x3e, 0x13, 0x64, 0x66, 0x77, 0x49, 0x90,
	0x41, 0x66, 0x30, 0xd9, 0x7f, 0xdc, 0x8f, 0xda, 0x30, 0x33, 0xb2, 0x18, 0x71, 0x63, 0xf6, 0x8d,
	0x39, 0xe7, 0xde, 0x73, 0x4f, 0x0e, 0x07, 0xc6, 0xc7, 0x60, 0x46, 0xe3, 0x8a, 0x3f, 0xcc, 0xa3,
	0x24, 0x4b, 0x49, 0xce, 0xfd, 0xa2, 0xa4, 0x9c, 0x22, 0x8b, 0x53, 0x4c, 0xc5, 0xe7, 0xe4, 0xe3,
	0x31, 0x98, 0x1d, 0x2a, 0x52, 0x3e, 0x46, 0x77, 0x69, 0xc6, 0x49, 0x29, 0x27, 0xbc, 0x25, 0xb8,
	0x8b, 0x92, 0xc4, 0x9c, 0x6c, 0x7e, 0xd4, 0xeb, 0x0b, 0xb1, 0x1d, 0x92, 0x43, 0x45, 0x18, 0x47,
	0x08, 0xfa, 0x79, 0xbc, 0x27, 0x8e, 0x36, 0xd5, 0xbe, 0x59, 0xa1, 0xf8, 0x46, 0x0e, 0x98, 0x98,
	0xf0, 0x38, 0xcd, 0x98, 0xa3, 0x0b, 0xf8, 0xf4, 0xf4, 0xd6, 0x30, 0xe9, 0x92, 0x62, 0x05, 0xcd,
	0x19, 0x41, 0x33, 0x30, 0xa4, 0x35, 0xb1, 0x36, 0x9c, 0xdb, 0x7e, 0xe3, 0xcd, 0x3f, 0x5b, 0x50,
	0x63, 0xde, 0x0a, 0xdc, 0xff, 0x05, 0xbe, 0xe2, 0xec, 0x45, 0x4d, 0xbb, 0x4d, 0xed, 0x33, 0x4c,
	0xba, 0xd4, 0xa4, 0x39, 0xef, 0x2f, 0x8c, 0x7f, 0x13, 0xde, 0x75, 0xe8, 0x13, 0x58, 0x52, 0x21,
	0x4a, 0xb1, 0xb8, 0xd5, 0x0f, 0xdf, 0x49, 0x60, 0x89, 0x91, 0x0d, 0x66, 0xc5, 0x48, 0x59, 0x53,
	0xba, 0xa0, 0x8c, 0xfa, 0xb9, 0xc4, 0xde, 0x1f, 0xb0, 0x2f, 0xf4, 0x2e, 0x72, 0xb8, 0xd1, 0xf9,
	0x16, 0xdc, 0x9f, 0x24, 0x23, 0xdd, 0x39, 0xbc, 0xcd, 0xde, 0x0e, 0xec, 0xb6, 0xd8, 0x2a, 0x65,
	0x8d, 0xa0, 0x0f, 0x86, 0xec, 0x87, 0xb2, 0x37, 0x6e, 0xd9, 0xdb, 0xd6, 0xf5, 0xf9, 0x25, 0xd8,
	0x50, 0x4d, 0x5d, 0xbf, 0xb1, 0x06, 0xe7, 0xf2, 0x86, 0xca, 0x20, 0x00, 0x53, 0x9a, 0x64, 0x8e,
	0x36, 0xed, 0xbd, 0x16, 0xc2, 0x69, 0xce, 0x0b, 0xc0, 0x6d, 0x13, 0x0b, 0x5a, 0xb5, 0x32, 0xfd,
	0x00, 0x83, 0xa4, 0x06, 0x54, 0x02, 0xf2, 0xe1, 0x3d, 0x69, 0x30, 0x6a, 0xef, 0xa0, 0xf7, 0xa0,
	0x37, 0x29, 0xe9, 0x29, 0x6e, 0xea, 0xad, 0x77, 0xd7, 0xbb, 0x77, 0x56, 0x6f, 0xf4, 0x05, 0x20,
	0x11, 0xf5, 0xc6, 0x11, 0xcd, 0x9d, 0xbe, 0x50, 0xb1, 0x14, 0xb2, 0xc9, 0x6b, 0xba, 0x12, 0x05,
	0x13, 0xf4, 0x40, 0xd2, 0x0a, 0xd9, 0xe4, 0xe8, 0x2b, 0x8c, 0x12, 0xba, 0x2f, 0xea, 0xff, 0x28,
	0x06, 0x0c, 0x31, 0x30, 0x6c, 0x30, 0xa9, 0xb0, 0x23, 0x19, 0xcd, 0xef, 0x59, 0xc4, 0xa9, 0x63,
	0x4a, 0x05, 0x85, 0xfc, 0xa3, 0x3b, 0x43, 0xc4, 0xf3, 0xfd, 0x39, 0x00, 0x00, 0xff, 0xff, 0xec,
	0x20, 0xc0, 0xbd, 0xec, 0x03, 0x00, 0x00,
}
