// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/user.proto

package todoproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	IsAdmin              bool     `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_644e625c59382b7a, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

type CreateUserResponse struct {
	Id                    uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username              string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	TwoFactorSecret       string   `protobuf:"bytes,3,opt,name=two_factor_secret,json=twoFactorSecret,proto3" json:"two_factor_secret,omitempty"`
	IsAdmin               bool     `protobuf:"varint,4,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	PasswordLastChangedOn uint64   `protobuf:"varint,5,opt,name=password_last_changed_on,json=passwordLastChangedOn,proto3" json:"password_last_changed_on,omitempty"`
	CreatedOn             uint64   `protobuf:"varint,6,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	UpdatedOn             uint64   `protobuf:"varint,7,opt,name=updated_on,json=updatedOn,proto3" json:"updated_on,omitempty"`
	ArchivedOn            uint64   `protobuf:"varint,8,opt,name=archived_on,json=archivedOn,proto3" json:"archived_on,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_644e625c59382b7a, []int{1}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateUserResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserResponse) GetTwoFactorSecret() string {
	if m != nil {
		return m.TwoFactorSecret
	}
	return ""
}

func (m *CreateUserResponse) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

func (m *CreateUserResponse) GetPasswordLastChangedOn() uint64 {
	if m != nil {
		return m.PasswordLastChangedOn
	}
	return 0
}

func (m *CreateUserResponse) GetCreatedOn() uint64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *CreateUserResponse) GetUpdatedOn() uint64 {
	if m != nil {
		return m.UpdatedOn
	}
	return 0
}

func (m *CreateUserResponse) GetArchivedOn() uint64 {
	if m != nil {
		return m.ArchivedOn
	}
	return 0
}

type UpdateUserPasswordRequest struct {
	OldPassword          string   `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	TotpToken            string   `protobuf:"bytes,3,opt,name=totp_token,json=totpToken,proto3" json:"totp_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserPasswordRequest) Reset()         { *m = UpdateUserPasswordRequest{} }
func (m *UpdateUserPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserPasswordRequest) ProtoMessage()    {}
func (*UpdateUserPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_644e625c59382b7a, []int{2}
}

func (m *UpdateUserPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserPasswordRequest.Unmarshal(m, b)
}
func (m *UpdateUserPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserPasswordRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserPasswordRequest.Merge(m, src)
}
func (m *UpdateUserPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserPasswordRequest.Size(m)
}
func (m *UpdateUserPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserPasswordRequest proto.InternalMessageInfo

func (m *UpdateUserPasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *UpdateUserPasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

func (m *UpdateUserPasswordRequest) GetTotpToken() string {
	if m != nil {
		return m.TotpToken
	}
	return ""
}

type UpdateUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_644e625c59382b7a, []int{3}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

type GetUserRequest struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_644e625c59382b7a, []int{4}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetUserByUsernameRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByUsernameRequest) Reset()         { *m = GetUserByUsernameRequest{} }
func (m *GetUserByUsernameRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByUsernameRequest) ProtoMessage()    {}
func (*GetUserByUsernameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_644e625c59382b7a, []int{5}
}

func (m *GetUserByUsernameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByUsernameRequest.Unmarshal(m, b)
}
func (m *GetUserByUsernameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByUsernameRequest.Marshal(b, m, deterministic)
}
func (m *GetUserByUsernameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByUsernameRequest.Merge(m, src)
}
func (m *GetUserByUsernameRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByUsernameRequest.Size(m)
}
func (m *GetUserByUsernameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByUsernameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByUsernameRequest proto.InternalMessageInfo

func (m *GetUserByUsernameRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetUserResponse struct {
	Id                    uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username              string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	IsAdmin               bool     `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	PasswordLastChangedOn uint64   `protobuf:"varint,4,opt,name=password_last_changed_on,json=passwordLastChangedOn,proto3" json:"password_last_changed_on,omitempty"`
	CreatedOn             uint64   `protobuf:"varint,5,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	UpdatedOn             uint64   `protobuf:"varint,6,opt,name=updated_on,json=updatedOn,proto3" json:"updated_on,omitempty"`
	ArchivedOn            uint64   `protobuf:"varint,7,opt,name=archived_on,json=archivedOn,proto3" json:"archived_on,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_644e625c59382b7a, []int{6}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetUserResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetUserResponse) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

func (m *GetUserResponse) GetPasswordLastChangedOn() uint64 {
	if m != nil {
		return m.PasswordLastChangedOn
	}
	return 0
}

func (m *GetUserResponse) GetCreatedOn() uint64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *GetUserResponse) GetUpdatedOn() uint64 {
	if m != nil {
		return m.UpdatedOn
	}
	return 0
}

func (m *GetUserResponse) GetArchivedOn() uint64 {
	if m != nil {
		return m.ArchivedOn
	}
	return 0
}

type DeleteUserRequest struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_644e625c59382b7a, []int{7}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UserListRequest struct {
	Filter               *QueryFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	UserId               uint64       `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UserListRequest) Reset()         { *m = UserListRequest{} }
func (m *UserListRequest) String() string { return proto.CompactTextString(m) }
func (*UserListRequest) ProtoMessage()    {}
func (*UserListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_644e625c59382b7a, []int{8}
}

func (m *UserListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListRequest.Unmarshal(m, b)
}
func (m *UserListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListRequest.Marshal(b, m, deterministic)
}
func (m *UserListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListRequest.Merge(m, src)
}
func (m *UserListRequest) XXX_Size() int {
	return xxx_messageInfo_UserListRequest.Size(m)
}
func (m *UserListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserListRequest proto.InternalMessageInfo

func (m *UserListRequest) GetFilter() *QueryFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *UserListRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UserListResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListResponse) Reset()         { *m = UserListResponse{} }
func (m *UserListResponse) String() string { return proto.CompactTextString(m) }
func (*UserListResponse) ProtoMessage()    {}
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_644e625c59382b7a, []int{9}
}

func (m *UserListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListResponse.Unmarshal(m, b)
}
func (m *UserListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListResponse.Marshal(b, m, deterministic)
}
func (m *UserListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListResponse.Merge(m, src)
}
func (m *UserListResponse) XXX_Size() int {
	return xxx_messageInfo_UserListResponse.Size(m)
}
func (m *UserListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserListResponse proto.InternalMessageInfo

func (m *UserListResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UserCountResponse struct {
	Count                uint64   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCountResponse) Reset()         { *m = UserCountResponse{} }
func (m *UserCountResponse) String() string { return proto.CompactTextString(m) }
func (*UserCountResponse) ProtoMessage()    {}
func (*UserCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_644e625c59382b7a, []int{10}
}

func (m *UserCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCountResponse.Unmarshal(m, b)
}
func (m *UserCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCountResponse.Marshal(b, m, deterministic)
}
func (m *UserCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCountResponse.Merge(m, src)
}
func (m *UserCountResponse) XXX_Size() int {
	return xxx_messageInfo_UserCountResponse.Size(m)
}
func (m *UserCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserCountResponse proto.InternalMessageInfo

func (m *UserCountResponse) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type User struct {
	Id                    uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username              string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	HashedPassword        string   `protobuf:"bytes,3,opt,name=hashed_password,json=hashedPassword,proto3" json:"hashed_password,omitempty"`
	TwoFactorSecret       string   `protobuf:"bytes,4,opt,name=two_factor_secret,json=twoFactorSecret,proto3" json:"two_factor_secret,omitempty"`
	IsAdmin               bool     `protobuf:"varint,5,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	PasswordLastChangedOn uint64   `protobuf:"varint,6,opt,name=password_last_changed_on,json=passwordLastChangedOn,proto3" json:"password_last_changed_on,omitempty"`
	CreatedOn             uint64   `protobuf:"varint,7,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	UpdatedOn             uint64   `protobuf:"varint,8,opt,name=updated_on,json=updatedOn,proto3" json:"updated_on,omitempty"`
	ArchivedOn            uint64   `protobuf:"varint,9,opt,name=archived_on,json=archivedOn,proto3" json:"archived_on,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_644e625c59382b7a, []int{11}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetHashedPassword() string {
	if m != nil {
		return m.HashedPassword
	}
	return ""
}

func (m *User) GetTwoFactorSecret() string {
	if m != nil {
		return m.TwoFactorSecret
	}
	return ""
}

func (m *User) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

func (m *User) GetPasswordLastChangedOn() uint64 {
	if m != nil {
		return m.PasswordLastChangedOn
	}
	return 0
}

func (m *User) GetCreatedOn() uint64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *User) GetUpdatedOn() uint64 {
	if m != nil {
		return m.UpdatedOn
	}
	return 0
}

func (m *User) GetArchivedOn() uint64 {
	if m != nil {
		return m.ArchivedOn
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "todoproto.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "todoproto.CreateUserResponse")
	proto.RegisterType((*UpdateUserPasswordRequest)(nil), "todoproto.UpdateUserPasswordRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "todoproto.UpdateUserResponse")
	proto.RegisterType((*GetUserRequest)(nil), "todoproto.GetUserRequest")
	proto.RegisterType((*GetUserByUsernameRequest)(nil), "todoproto.GetUserByUsernameRequest")
	proto.RegisterType((*GetUserResponse)(nil), "todoproto.GetUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "todoproto.DeleteUserRequest")
	proto.RegisterType((*UserListRequest)(nil), "todoproto.UserListRequest")
	proto.RegisterType((*UserListResponse)(nil), "todoproto.UserListResponse")
	proto.RegisterType((*UserCountResponse)(nil), "todoproto.UserCountResponse")
	proto.RegisterType((*User)(nil), "todoproto.User")
}

func init() { proto.RegisterFile("v1/user.proto", fileDescriptor_644e625c59382b7a) }

var fileDescriptor_644e625c59382b7a = []byte{
	// 568 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x51, 0x6f, 0xd3, 0x3c,
	0x14, 0x55, 0xb2, 0x36, 0x6d, 0x6e, 0xbf, 0xaf, 0xa5, 0xd1, 0x06, 0xd9, 0xa4, 0x89, 0x12, 0x09,
	0xd1, 0x21, 0xd4, 0x69, 0x43, 0x02, 0xf1, 0x08, 0x45, 0x43, 0x48, 0x93, 0x0a, 0x81, 0xbe, 0xf0,
	0x62, 0x99, 0xd8, 0xa5, 0x11, 0x9d, 0xdd, 0xc5, 0x6e, 0xab, 0xbd, 0xf1, 0x4f, 0xf8, 0x1f, 0xfc,
	0x2a, 0x7e, 0x02, 0xb2, 0x1d, 0xa7, 0x4d, 0x61, 0x6d, 0xe1, 0xad, 0xf7, 0x9c, 0x53, 0xdf, 0x9b,
	0x7b, 0x8e, 0x0d, 0xff, 0xcf, 0xcf, 0x4e, 0x67, 0x82, 0x66, 0xbd, 0x69, 0xc6, 0x25, 0x0f, 0x7c,
	0xc9, 0x09, 0xd7, 0x3f, 0x8f, 0x0e, 0xe6, 0x67, 0xa7, 0xd7, 0x33, 0x9a, 0xdd, 0xa0, 0x51, 0x3a,
	0x91, 0x56, 0x11, 0x8d, 0xa0, 0xdd, 0xcf, 0x28, 0x96, 0x74, 0x28, 0x68, 0x16, 0xd3, 0xeb, 0x19,
	0x15, 0x32, 0x38, 0x82, 0xba, 0x3a, 0x84, 0xe1, 0x2b, 0x1a, 0x3a, 0x1d, 0xa7, 0xeb, 0xc7, 0x45,
	0xad, 0xb8, 0x29, 0x16, 0x62, 0xc1, 0x33, 0x12, 0xba, 0x86, 0xb3, 0x75, 0x70, 0x08, 0xf5, 0x54,
	0x20, 0x4c, 0xae, 0x52, 0x16, 0xee, 0x75, 0x9c, 0x6e, 0x3d, 0xae, 0xa5, 0xe2, 0xa5, 0x2a, 0xa3,
	0xef, 0x2e, 0x04, 0xab, 0x8d, 0xc4, 0x94, 0x33, 0x41, 0x83, 0x26, 0xb8, 0x29, 0xd1, 0x3d, 0x2a,
	0xb1, 0x9b, 0x92, 0x52, 0x67, 0x77, 0xad, 0xf3, 0x63, 0x68, 0xcb, 0x05, 0x47, 0x23, 0x9c, 0x48,
	0x9e, 0x21, 0x41, 0x93, 0x8c, 0x4a, 0xdd, 0xc6, 0x8f, 0x5b, 0x72, 0xc1, 0x2f, 0x34, 0xfe, 0x41,
	0xc3, 0xa5, 0x49, 0x2a, 0xa5, 0x49, 0x82, 0xe7, 0x10, 0xda, 0x81, 0xd1, 0x04, 0x0b, 0x89, 0x92,
	0x31, 0x66, 0x5f, 0x28, 0x41, 0x9c, 0x85, 0x55, 0x3d, 0xc8, 0x81, 0xe5, 0x2f, 0xb1, 0x90, 0x7d,
	0xc3, 0x0e, 0x58, 0x70, 0x0c, 0x90, 0xe8, 0x2f, 0xd0, 0x52, 0x4f, 0x4b, 0xfd, 0x1c, 0x31, 0xf4,
	0x6c, 0x4a, 0x2c, 0x5d, 0x33, 0x74, 0x8e, 0x0c, 0x58, 0x70, 0x1f, 0x1a, 0x38, 0x4b, 0xc6, 0xe9,
	0xdc, 0xf0, 0x75, 0xcd, 0x83, 0x85, 0x06, 0x2c, 0xfa, 0xe6, 0xc0, 0xe1, 0x50, 0xcb, 0xd5, 0x86,
	0xde, 0xe5, 0x23, 0x58, 0x4b, 0x1e, 0xc0, 0x7f, 0x7c, 0x42, 0x50, 0xb1, 0x7a, 0x63, 0x4b, 0x83,
	0x4f, 0x88, 0x55, 0x2a, 0x09, 0xa3, 0x0b, 0xb4, 0xe6, 0x4e, 0x83, 0xd1, 0x45, 0x21, 0x39, 0x06,
	0x90, 0x5c, 0x4e, 0x91, 0xe4, 0x5f, 0x29, 0xcb, 0x77, 0xe7, 0x2b, 0xe4, 0xa3, 0x02, 0xa2, 0x7d,
	0x08, 0x96, 0x13, 0x58, 0x8f, 0xa2, 0x13, 0x68, 0xbe, 0xa1, 0x72, 0x35, 0x1f, 0xf7, 0xa0, 0xa6,
	0x5c, 0x41, 0x85, 0x75, 0x9e, 0x2a, 0xdf, 0x92, 0xe8, 0x19, 0x84, 0xb9, 0xf4, 0xd5, 0xcd, 0x30,
	0xf7, 0x6d, 0x87, 0x50, 0x45, 0x3f, 0x1d, 0x68, 0x15, 0x3d, 0xfe, 0x21, 0x1a, 0xb7, 0x07, 0x6f,
	0xa3, 0xdd, 0x95, 0xdd, 0xed, 0xae, 0x6e, 0xb6, 0xdb, 0xdb, 0x62, 0x77, 0xed, 0x37, 0xbb, 0x9f,
	0x40, 0xfb, 0x35, 0x9d, 0xd0, 0xf2, 0xc5, 0xbb, 0x75, 0xb1, 0x9f, 0xa0, 0xa5, 0x74, 0x97, 0xa9,
	0x90, 0x56, 0xdb, 0x03, 0xcf, 0xdc, 0x64, 0x2d, 0x6d, 0x9c, 0xdf, 0xed, 0x15, 0x97, 0xbd, 0xf7,
	0x5e, 0x5d, 0xf4, 0x0b, 0xcd, 0xc6, 0xb9, 0x6a, 0xf5, 0x6c, 0xb7, 0x74, 0xf6, 0x0b, 0xb8, 0xb3,
	0x3c, 0x3b, 0x5f, 0xfe, 0x43, 0xa8, 0x2a, 0x56, 0x84, 0x4e, 0x67, 0xaf, 0xdb, 0x38, 0x6f, 0xad,
	0x9c, 0xad, 0xe7, 0x35, 0x6c, 0x74, 0x02, 0x6d, 0x55, 0xf6, 0xf9, 0x8c, 0x2d, 0xff, 0xbb, 0x0f,
	0xd5, 0x44, 0x01, 0xf9, 0x27, 0x98, 0x22, 0xfa, 0xe1, 0x42, 0x45, 0x69, 0xff, 0xca, 0xd7, 0x47,
	0xd0, 0x1a, 0x63, 0x31, 0xa6, 0x2b, 0xc1, 0x37, 0xa1, 0x6d, 0x1a, 0xb8, 0x08, 0xf6, 0x1f, 0xdf,
	0x86, 0xca, 0xf6, 0xb7, 0xa1, 0xba, 0x7b, 0x58, 0xbc, 0xdd, 0xc3, 0x52, 0xdb, 0x1c, 0x96, 0xfa,
	0x96, 0xb0, 0xf8, 0xeb, 0x61, 0xf9, 0xec, 0xe9, 0xd5, 0x3f, 0xfd, 0x15, 0x00, 0x00, 0xff, 0xff,
	0xd7, 0xad, 0x30, 0x88, 0xdf, 0x05, 0x00, 0x00,
}
